### ISSUE TITLE
[BUG]Missing scripts on GameObjects

### ISSUE THREAD

**Issue by sonicv6** [AoTTG-2/AoTTG-2#101]
**Describe the bug**
Numerous GameObjects have missing scripts.

**To Reproduce**
1. Load AoTTG 2 in Unity Editor.
2. Load up any level.
3. Observe the many, many missing scripts in console.

**Expected behavior**
All GameObjects should have the associated scripts attached.

**Comment by DjFrytek** [comment]
**List of objects with missing scripts**

**Main Menu**
>"VERSION" missing one script
>"AOTTG_HERO 1" 3 object with missing scripts (most likely not relevant because those are just player models in old main menu)
>"Gas" inside of InGameUi missing one script.
>"COLOSSAL_TITAN" missing one script, (most likely not relevant because it's a model in old main menu)

**The City - Classic | Titans**
>"MainCamera" missing 3 scripts.

**The Forest | Waves / Annie**
>"MainCamera" missing scripts like previously.

**Trost | Eren | Colossal**
>"TITAN_EREN_trost" missing 2 scripts.
>"MainCamera" missing scripts like previously.

**Akina**
>"MainCamera" missing scripts like previously.

**Outside the walls**
>"Terrain" missing 1 script
>"MainCamera" missing scripts like previously.
