### ISSUE TITLE
Hero Skill: Blade Throw

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#107]
**Is your feature request related to a problem? Please describe.**
The player throws his blades in one direction, which can damage a titan for X damage if aimed correctly.

**Describe the solution you'd like**
A new skill where the player can throw blades as an expensive but safe alternative to slightly damage a titan

- [x] Confirm if #33 is done
- [ ] #741
- [x] Implement the blade skill
- [x] Throwing blades can kill players if PvP is enabled
- [x] If the blades hit the titan nape, it does 10% damage (based on your speed)

**Comment by Alex-Mod-Bot152** [comment]
**Idea by @IRI and @Cheese respectively** 

Being able to retrive the blades 

Blades could get stuck in titans and if retriving them is a option there would be animation for doing it 

**Alex-Mod-Bot note**

After retriving the blades they would have decreased durability and there would be no animation if titans have already vaporized

**Comment by Lithrun** [comment]
> 
> 
> **Idea by @iri and @cheese respectively**
> 
> Being able to retrive the blades
> 
> Blades could get stuck in titans and if retriving them is a option there would be animation for doing it
> 
> **Alex-Mod-Bot note**
> 
> After retriving the blades they would have decreased durability and there would be no animation if titans have already vaporized

Don't think we should implement this due to balancing issues, nor do we need such a mechanic & animation as it will make things more complex than they have to be.

**Comment by Alex-Mod-Bot152** [comment]
I understand. I just wanted to write IRI and Cheese idea and what they think about it. Balancing the special is something that should be done so I agree with you. If needed we can discuss this further

**Comment by Prolonpo** [comment]
From @Alex-Mod-Bot152, this skill should be available for all blade wielders in Human vs Human Pvp Scenarios.

https://discord.com/channels/681641241125060652/681647375336341522/791412867386572851

**Comment by PeteAniDev** [comment]
Idea: If the blades hit the titan nape, it does 10% (at 0% durability) ~ 50% (at 100% durability) damage (based on your speed). Since this is kind of like the AHSS skill, I suppose it should deal somewhat the same damage.

**Comment by PeteAniDev** [comment]
- [x] Better blade flying direction when raycasting hit nothing.

**Comment by PeteAniDev** [comment]
- [x] Weapon trail on blades.

**Comment by PeteAniDev** [comment]
- [x] Set a constant minimum damage
- [ ] Reloading bug https://discord.com/channels/681641241125060652/683082467069919236/909917199383298158. Should be solved in #752
