### ISSUE TITLE
Time & Lighting System

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#113]
**Is your feature request related to a problem? Please describe.**
Develop a system which works on a day-night cycle. Players can configure how long a day lasts, and based on that setting, the game will automatically change its time. In the morning the sunset, and during the evening there's the sunset. During night it should be dark, so that players would have to make use of items such as torches or lanterns.

- [x] Synch Multiplayer Lobby time and lighting with all players
- [x] Add options to define the duration/interval, set time and to freeze time
- [x] Investigate on how titan AI should be affected by this

**Comment by FAStre** [comment]
issue is not stale, last commit is https://github.com/AoTTG-2/AoTTG-2/pull/340/commits/3746789b746b4e42706b5093e505c2a75a9bd6b4

**Comment by FAStre** [comment]
Not stale, check #340
