### ISSUE TITLE
[BUG]No interaction wheel

### ISSUE THREAD

**Issue by Jacko340** [AoTTG-2/AoTTG-2#128]
**Bug:**
There is no interaction wheel when there is supposed to be one.

**How to Reproduce:**
1. Go to City.
2. Go to the gas station.
3. Press F to open the interaction wheel.
4. No interaction wheel appears.

**Expected behaviour:**
The interaction wheel is supposed to appear.

**Log file:**
[NoInteractionWheel.txt](https://github.com/AoTTG-2/AoTTG-2/files/4612611/NoInteractionWheel.txt)
[interactionwheelbug_output_log.txt](https://github.com/AoTTG-2/AoTTG-2/files/4612632/interactionwheelbug_output_log.txt)

**Additional context:**
The interaction wheel should work in the City.

**Comment by Lithrun** [comment]
Supply stations on all maps should now have interaction wheel. #101
