### ISSUE TITLE
[BUG] In-game cursor disappears 

### ISSUE THREAD

**Issue by KoroSensei0320** [AoTTG-2/AoTTG-2#130]
**Describe the bug**
The ingame cursor disappears in **Test Zone ** if you change camera. Same problem arises if you enter settings and then exit.

**To Reproduce**
Steps to reproduce the behaviour:
1. Host a server using any map.
2. Press C to change camera OR enter then exit settings.
3. See error - this hides the crosshair and shows your OS cursor. The cursor still works to fire hooks.

**Expected behavior**
It is expected that the crosshair shows up visually for all camera modes.

**Log file**
[output_log.txt](https://github.com/AoTTG-2/AoTTG-2/files/4612761/output_log.txt)

Additional info: 
The crosshair constantly works for TPS, but only for that camera view.

**Comment by JupiterJaeden** [comment]
Upon further study, it seems we are dealing with 2 separate (although not entirely unrelated) bugs. 

Bug 1: Opening the menu makes hardware cursor visible, as expected. However, closing the menu causes the in-game reticle to disappear and hardware cursor remains visible. 
Bug 2: Switching camera modes causes in-game reticle to disappear and hardware cursor to become visible. However, switching to the TPS camera mode fixes this. 

I will attempt to solve both of these bugs, starting with bug 1.
