### ISSUE TITLE
[BUG] Settings interface bug

### ISSUE THREAD

**Issue by KoroSensei0320** [AoTTG-2/AoTTG-2#131]
**Describe the bug**
The player registers keystrokes and mouse movements (camera turning and attacking with each click) even if the settings interface is open.

**To Reproduce**
1. Host/join a server (any map)
2. Open the settings interface
3. Click on any buttons - it will still register as a character's movement. Clicking a button will attack ingame, which could cause you to fall off a tree whilst changing settings. (All keystrokes register)

**Expected behaviour**
Keystrokes should not register whilst in settings.

**Comment by KoroSensei0320** [comment]
(Confirmed on PC by others on the Testing Team. I didn't confirm a bug for my own issue)

**Comment by Lithrun** [comment]
Known issue in #60
