### ISSUE TITLE
[BUG] 25 titans spawn on first wave in Forest and City

### ISSUE THREAD

**Issue by SlowDeepExhalation** [AoTTG-2/AoTTG-2#134]
**Bug:** 25 titans spawn on wave 1 in Forest waves and City waves.  One tester has found that on wave 2, only 4 titans spawn.  Occurs on build "Issue126&127".

**To Reproduce:**  Start a Forest waves or City waves game.  Current titans will be 25, and you will rapidly be surrounded.

**Expected behavior:**
Both game modes should start with only 3 titans.

**Additional Information:**
This is a newly introduced bug.  It does not occur on build "Issue128".

Log file attached, containing only the player spawning into forest waves:
[output_log 25 titans spawn into forest waves.txt](https://github.com/AoTTG-2/AoTTG-2/files/4623936/output_log.25.titans.spawn.into.forest.waves.txt)

**Comment by SlowDeepExhalation** [comment]
A tester completed the first wave again, to get an output log from after the second wave spawns only four titans.  Log file attached:
[output_log Forest25spawnWave2has4spawn.txt](https://github.com/AoTTG-2/AoTTG-2/files/4624045/output_log.Forest25spawnWave2has4spawn.txt)

**Comment by Lithrun** [comment]
Bug report itself is not a bug, as titans are configured to spawn with 25 in that build. The comment is an issue however, so that's resolved in #36

**Comment by Lithrun** [comment]
Included in #170
