### ISSUE TITLE
[BUG]Cloning your character

### ISSUE THREAD

**Issue by desu7** [AoTTG-2/AoTTG-2#136]
**Describe the bug**
You can clone your character if you restart the game at the same time you respawn.

**To Reproduce**
1. Create a new server, map doesn't matter as long as there is any factor that kills you.
2. Die.
3. Game Restart text will appear, while this happens type /restart in the chat.
4. Press enter just when the count hits 3, your character will respawn at the same time you restart the game, creating a clone (you can only have 1).

**Expected behavior**
Restarting at the same time you respawn shouldn't create a clone of your character.

**Screenshots**
https://imgur.com/9rbCYd1

**Log file**
Same log as #137 as this other bug was unexpected.
https://pastebin.com/eNu8KJiY

**Additional context**
Video: https://youtu.be/BtQJoxOXiPU

**Comment by SlowDeepExhalation** [comment]
Duplicated in RCFinal; added low priority.
