### ISSUE TITLE
[BUG]Getting stuck in Gas Supply in The City map

### ISSUE THREAD

**Issue by desu7** [AoTTG-2/AoTTG-2#137]
**Describe the bug**
If you go fast enough you can get stuck in the gas supply and you can't go out.

**To Reproduce**
1. Host a server in The City map.
2. Get far from the supply to gain speed.
3. Get enough speed and place yourself between the supply and the right house near spawn.
4. If done right, you'll get stuck and you won't be able to get out.

**Expected behavior**
You shouldn't get stuck in the gas supply.

**Screenshots**
https://imgur.com/gKKH1VP

**Log file**
As it happened in the same game as issue #136, it's the same log.
https://pastebin.com/eNu8KJiY

**Additional context**
Video: https://www.youtube.com/watch?v=BtQJoxOXiPU

**Comment by SlowDeepExhalation** [comment]
Duplicated in RCFinal; Added Low Priority as it's a holdover from RC code.
