### ISSUE TITLE
[BUG] Heavy slowdown when spawning titans in Waves mode

### ISSUE THREAD

**Issue by SlowDeepExhalation** [AoTTG-2/AoTTG-2#151]
**Describe the bug**
Upon clearing a wave of titans in either Waves game mode (Forest or City), the game lags for a split second as it spawns the new titans.  The lag gets longer the more titans are spawned.

Seemingly, the core bug is that spawning titans is much more resource intensive than in RCmod.

**To Reproduce**
1. Play forest or city waves.
2. Kill all three titans in the first wave.
3. Note that there's a brief moment of lag before the new titans spawn.  Continue killing waves to get more demonstrations.

**Expected behavior**
No lag should be noticeable for small amounts of titans, especially not on higher end computers.

**Additional Information**
Build: Issue144-145
This bug DOES exist in RC mod, but the lag is far, far less noticeable; the lag from spawning only four titans in AoTTG 2 is similar to the lag from spawning fifty in RC, if not higher.

Output log attached, the only thing I did was start a forest server, then kill three titans to end the wave.
[output_log forest waves titan spawn slowdown.txt](https://github.com/AoTTG-2/AoTTG-2/files/4656752/output_log.forest.waves.titan.spawn.slowdown.txt)

**Comment by Lithrun** [comment]
This is related to #36.
The way titans are spawned is that they have their collision hitboxes enabled by default. Their collision hitboxes result into various frame drops, so these are only activated once the player is within range. There's a method within the Awake that disables these hitboxes, but this happens after the objects are initialized. So for a few frames, you will have a large amount of moving colliders.

My theory is that if these hitboxes are disabled by default on the prefab, that spawning titans should not cause significant frame drops. Will see tonight if that's correct or not

**Comment by Lithrun** [comment]
As noticed from Testing Team, spawning titans in a coroutine performs better compared to spawning them via a for loop.
