### ISSUE TITLE
Move Art Team issues to the repository

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#152]
**How will this enhancement improve the game?**
Art team has finished several issues, but have not committed their work to Github.

**Describe the solution you'd like**
Art Team should commit their work to Github, which will happen for future issues. For now, the closed ones have to be moved to Github.

- [x] Contact @Lithrun to gain access to the art team channels, as their work can be found there
- [ ] Commit #64, #66, #87, #88 and #89 to the repository

**Comment by Lithrun** [comment]
Awaiting missing files from @AoTTG-2/art-team. Remove On Hold label once files are recovered.

**Comment by roxnsteady** [comment]
Working on it.

- [ ] Add + Organize all issues from Trello to Github
- [ ] Add the missing files
- [ ] Arrange the Board to make it easy to understand

**Comment by roxnsteady** [comment]
Additional help will be appreciated. Thank you!

**Comment by Lithrun** [comment]
Assets are being moved over to Github, so this one can be considered done
