### ISSUE TITLE
.gitignore csproj files

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#157]
**Is your feature request related to a problem? Please describe.**
It is speculated that csproj files are automatically generated by Unity, so we can add them to our .gitignore

**Describe the solution you'd like**
Investigate if csproj files are automatically generated by Unity, and if they are, add them to the .gitignore

**Comment by mwnDK1402** [comment]
I usually use [this](http://gitignore.io/api/unity) without any problems.

**Comment by mwnDK1402** [comment]
[I think we should just exclude them.](https://gamedev.stackexchange.com/questions/50187/are-sln-csproj-usefull-for-sharing-the-unity-project)
