### ISSUE TITLE
Difficulty Settings & Titan Abstraction

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#160]
**How will this enhancement improve the game?**
Within AoTTG, the difficulty setting has an impact on titan their speed and animation speed. On some maps, bosses have higher health, and also have the increased speed as aforementioned. 

**Describe the solution you'd like**
An improved difficulty system which is managed within the GamemodeBase class instead of via the IN_GAME_MAIN_CAMERA class

- [x] Confirm #36 is done
- [x] Investigate which gamemodes should have different logic depending on the difficulty. For instance, if the capture gamemode is played on hard difficulty, should titans start with 4 spawn points instead of 3? Discuss findings with @AoTTG-2/development-team 
- [x] Add difficulty options: "Easy", "Normal", "Hard" and "Abnormal".
- [x] Remove any IN_GAME_MAIN_CAMERA.difficulty references and replace this with a new Gamemode Difficulty setting.
- [x] Extend the Titan Configuration class to accept a difficulty enum, which will increase / decrease some of its attributes.
- [x] Reintroduce titan "wait" timers, which are influenced by difficulty.

**Comment by mwnDK1402** [comment]
We talked about making the new difficulty code more extensible by using ScriptableObjects. Consider writing the conclusion here, so that it will be easier to discuss and implement later.

**Comment by Lithrun** [comment]
Already started experimenting with Zenject, after that ScriptableObjects will do. (After I return from vacation) But thanks for the reminder

**Comment by Lithrun** [comment]
Issue currently on hold until the titan models & animations are ready for a final overhaul to the titans.

**Comment by Lithrun** [comment]
New titan models & animations are no longer included within this issue.

**Comment by Lithrun** [comment]
New titan design: [Link](https://docs.google.com/document/d/128f8NIFafj6FeefGxUgdj42_goJ3GEsFBr-cYypHW1s/edit?usp=sharing)

Summary of discussion:
- Difficulties will be reworked. Every setting related to difficulties, together with various hidden settings, will get exposed. AoTTG2 will be delivered with 5 difficulty presets (Easy, Normal, Hard, Abnormal and Extreme) based on how we think that the game should be played. Players have the ability to create a Custom difficulty and modify that to however they please. Custom difficulties can also be exported and imported, and in the future via a database.
- Factions are going to be introduced. Titans are associated with a faction and will attack any entity (titan, human, horse) of a different faction. This does also mean that a titan PvP gamemode will be introduced.
- Titans will be abstracted further. This does mean that every titan has the same base class (every titan can be controlled by players, is associated with a faction, has replaceable bodyparts (this is only within the code, art team needs to upgrade models first), a list of attacks, behavior scripts and the same attributes (Focus, health, speed, size ect)). This does mean for instance the players can attack Eren Titan if Eren is in a different faction, but also that players can control bosses such as the female or colossal titan eventually.
- Additional game settings will be introduced. The community should think of various settings that can be added to enhance the game further
