### ISSUE TITLE
[UI] Kill feed Resolution scaling

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#167]
**How will this enhancement improve the game?**
The kill feed is tied to the screen height, different resolutions can have the kill feed in the middle of their screen. It should be anchored to the top of the screen

**Describe the solution you'd like**
A kill feed that displays messages at the top regardless of the player their resolution. When testing the fix for this issue, please test it through different resolutions to verify that it has been fixed

**Comment by Acros5542** [comment]
Since this is one of the most frequently noticed issues by new testers, I'm adding the bug label for the sake of simplicity when I reference this post.

**Comment by nolanrdavenport** [comment]
This issue was resolved in #537
