### ISSUE TITLE
[BUG] titanRepawn tag NullReferenceException with Capture Gamemode's Checkpoints

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#175]
**Describe the bug**
Within the existing logic, a NullReferenceException can occur when a map supports the Capture Gamemode, but uses another gamemode. When spawning titans, the logic looks for any gameobjects with the titanRespawn tag, this gets called during OnLevelWasLoaded. The checkpoints will destroy themselves on Start, but this is problematic for spawning titans. It first found the titanRespawn tags, but Checkpoints destroy themselves after OnLevelWasLoaded. This leads to NullReferenceExceptions.

**To Reproduce**
1. Host any map which support the capture gamemode (City, Outside the Walls, Utgard)
2. Use the KillTitansGamemode
3. Attempt to spawn 100 titans
4. A null reference exception will occur and the logic stops spawning titans.

**Expected behavior**
It is expected that checkpoints destroy themselves before OnLevelWasLoaded is called, which means that the code has to be refactored to allow usage of Awake

**Comment by anthonyl6** [comment]
Ignore this mention accidentally applied a stash for this issue into #96 a few days ago

**Comment by Lithrun** [comment]
Unable to reproduce anymore as per 4th of June. Review this issue again at the 18th of June. If testing team does not notice any issue between 4th - 18th nor if we can reproduce it at the 18th, then it's fair to assume that this is solved.
