### ISSUE TITLE
[BUG] Reel-in feels unresponsive, especially with default controls

### ISSUE THREAD

**Issue by SlowDeepExhalation** [AoTTG-2/AoTTG-2#179]
**Describe the bug**
Reeling in feels unresponsive to many testers, including some who are used to playing with default controls.  The responsiveness seems to go up when performing critical reel ins (reeling in the moment a hook lands), and goes down when orbiting around an object; this may be related to issue #97 .

Rebinded reel in using AutoHotKey (which causes another key to send many WheelDown events, as if the player were scrolling the mousewheel extremely fast) *seems* to be more reliable than normal mousewheel scrolling, but some still report unresponsiveness.  Since rebinds *aren't actually implemented*, it's impossible to determine whether the rebinded unresponsiveness is due to AHK or AoTTG 2.

**To Reproduce**
The bug has no true reproduction method; testers *feel* like it's wrong, but it's not nonfunctional, just unreliable.  So, play forest and reel between trees.  Pay attention to the timing of successful reels.  It often feels late.

**Additional comments**
Confirmed on Issue98

May be related to the old AoTTG bug where higher FPS causes reeling to be less responsive because it has to happen on one of the frames where the game actually checks input.  We cannot easily compare how the game performs at different FPS rates due to Issue #178
May be related to Issue #97, since critical reels work better.
*Please* implement rebinds.  The current situation is just terrible.

**Comment by Lithrun** [comment]
Developer translation: Reeling should use Update instead of FixedUpdate. Should be a relatively easy fix, but please assure that you are converting any Time.FixedDelta to Time.Delta while moving the code.
