### ISSUE TITLE
Discord Rich Presence (DRP) integration

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#190]
**Is your feature request related to a problem? Please describe.**
Discord is one of the largest social platforms for gamers. It has a feature named Rich Presence, which allows users to see what games their friends are playing, but also show some additional information. An example of this is 
![image](https://user-images.githubusercontent.com/22615133/84828722-9e816400-b07a-11ea-9075-a39493767839.png)

**Describe the solution you'd like**
A Discord Rich Presence integration which displays various information (See below) of what the user is currently playing.

- [x] Region
- [x] Lobby name
- [x] Lobby gamemode & level information (Example: The Forest - Waves, Utgard Castle - Capture ect.)
- [x] Current / Max Players
- [x] An option to join the lobby that the discord user is playing. If it is public, then the user can automatically join. If it's hosted by Custom or contains a password, then an "Ask To Join" request has to be sent.

**Comment by alerithe** [comment]
I might be able to help on this issue considering my own mod already has Rich Presence.
