### ISSUE TITLE
Adding Missing Audio

### ISSUE THREAD

**Issue by MrLurkin** [AoTTG-2/AoTTG-2#196]
Find and add all audio not implemented into #98 

- [x] Footsteps

**Comment by 8veStory** [comment]
Will use Unity's animation events to get this done. Here's a preemptive list of the animations that will need to be done:

**Mindless Titan**
- [x] run_walk
- [x] turn_around1
- [x] turn_around2

**Abnormal Titan**
- [x] Run_abnormal
- [x] Run_abnormal0
- [x] Run_abnormal1

**Female Titan**
- [x] ~~ft_run~~ (seems like footstep sounds for female titan have already been implemented).

**Crawler**
- [x] crawler_run

**Eren Titan**
- [x] run
- [x] rock_walk
