### ISSUE TITLE
Update default AoTTG player costume to higher resolution

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#2]
**How will this enhancement improve the game?**
Currently player skins are of an old and outdated resolution.

**Describe the solution you'd like**
A higher resolution and better looking skin, compared to the current ones

**Describe alternatives you've considered**
N/A

**Additional context**
Default AoTTG skins are located within:

Assets/Resources/newtexture

**Comment by Lithrun** [comment]
Additionally, please investigate texture resolution down scaling as a graphical option @AoTTG-2/art-team

**Comment by KoroSensei0320** [comment]
Being worked on by ErenG. The artist doesn't have a GitHub yet.

**Comment by ghost** [comment]
Would we have to augment the number of tris to get better resolution or just update the textures to better quality?

**Comment by KoroSensei0320** [comment]
Just textures (at least for now) but this issue is already being worked on.

**Comment by KoroSensei0320** [comment]
Just textures (at least for now) but this issue is already being worked on.

**Comment by Lithrun** [comment]
Most textures have been improved with a higher resolution support. Still some are missing however

**Comment by KoroSensei0320** [comment]
[Costumes.zip](https://github.com/AoTTG-2/AoTTG-2/files/5114267/Costumes.zip)
[Player_Skin.zip](https://github.com/AoTTG-2/AoTTG-2/files/5114215/Player_Skin.zip)
[Hairs.zip](https://github.com/AoTTG-2/AoTTG-2/files/5114218/Hairs.zip)

**Comment by KoroSensei0320** [comment]
@Lithrun See the above files.

**Comment by Lithrun** [comment]
Moving these within #33 (https://github.com/AoTTG-2/AoTTG-2/commit/807655f34318cecf3dd891215a8e4b6b7b0b61f9)
