### ISSUE TITLE
[BUG] Hook sound effect distortion upon high speed

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#205]
**Describe the bug**
Within AoTTG, when the user goes with high speed, the sound effect of the hook will go into a higher pitch. However, in AoTTG2 this only sometimes occurs. What happens instead, is that the hook sound receives a lower and thus distorted pitch.

**To Reproduce**
1. Host a lobby
2. Try to fly around with 1-2k speed
3. The hook sound effect will sound distorted

**Expected behavior**
It is expected that the hook sound effects receives a higher pitch, and works identical to AoTTG.

**Comment by nolanrdavenport** [comment]
What I noticed is that whenever you grapple in the direction of your characters velocity, then the pitch gets lower, but if you grapple in a direction opposite to your characters velocity, then the pitch becomes higher. This seems to happen both with AOTTG and AOTTG2. The effect seems to be greater on AOTTG2 meaning it is more noticeable.

**Comment by nolanrdavenport** [comment]
It turns out that the reason the grappling hook was so distorted was because it had a doppler effect. I just lowered the doppler level from 1 to 0.25 and now it sounds much better at higher speeds.

**Comment by nolanrdavenport** [comment]
I also did the same with the slash because it also distorts at higher speeds.
