### ISSUE TITLE
Disabling Crawler Eye cutting

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#207]
**How will this enhancement improve the game?**
Currently, players can damage the eyes of crawlers. This should not happen, since defeating crawlers is very simple because of this small oversight.

**Describe the solution you'd like**
Humans should not be able to cut the eyes of crawlers.

- [x] Navigate to a class named "MindlessTitan", and modify the OnEyeHitRpc, so that nothing will happen if the current MindlessTitan is of type: MindlessTitanType.Crawler.

**Comment by Revaneuh** [comment]
*Sorry
