### ISSUE TITLE
[BUG] Titan Collision Misconfiguration

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#22]
**Describe the bug**
Titan Collisions don't work as intended because their layers aren't setup correctly. Whereas some layers are meant to be ignored, they are now used as physical collisions.

**To Reproduce**
1. Spawn into the game
2. Engage a titan, you will see that its collisions are different

**Expected behavior**
Titan collisions should be the same as in AoTTG. You should Project Settings at: Edit / Project Settings / Physics. At that page, experiment and apply the correct configuration. You might also want to check the Titan's prefab (TITAN_VER3.1) and see if its collisions are setup correctly

**Comment by sonicv6** [comment]
Weird blade collisions are fixed. However, hooks remain problematic.

**Comment by Lithrun** [comment]
Issue resolved as per #39.
