### ISSUE TITLE
Melee Weapon Trail

### ISSUE THREAD

**Issue by xXXConkerXXx** [AoTTG-2/AoTTG-2#223]
**How will this enhancement improve the game?**
This enhancement should fix the old X-WeaponTrail issue.

**Describe the solution you'd like**
Hopefully this should solve our WeaponTrail problems.

**Describe alternatives you've considered**
The alternative is creating the WeaponTrail by scratch.

**Additional context**
https://assetstore.unity.com/packages/tools/particles-effects/melee-weapon-trail-1728

**Comment by Lithrun** [comment]
Issue was already merged as per #701
