### ISSUE TITLE
[BUG] Issue versioning multiplayer conflicts

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#229]
**Describe the bug**
Since the introduction of the version manager, testers are able to join lobbies of different issue versions. This is not intentional, since if players with two different versions play together, things will break. Additionally, it is also not desired that testers are able to join lobbies of an issue that a developer is working on.

**Expected behavior**
It is expected that players with the same issue number can play together, without being able to see lobbies of players with a different issue number.

**Comment by Mi-Sad** [comment]
well this is kind of a weird thing we can fix it sliply just by using the issue number as an additional code to the version when connecting to photon, gonna just check how to retrive the current branch id from the code itself cos frankly i have no idea where that value is stored in the local files rn

**Comment by Mi-Sad** [comment]
Ok, checked the code a little bit and apparently there's already a code which try to get the current branch and if that part of code works everything else will, as that would set the version which is already setted for the photon connection to master server, so gonna start from there

**Comment by mwnDK1402** [comment]
I was about to mention it. You're referring to [this](https://github.com/AoTTG-2/AoTTG-2/blob/c81bfb4510bc5bfb6f234be7c43f558a97b6a3db/Assets/Scripts/VersionManager.cs), right?

**Comment by Acros5542** [comment]
I believe this should be closed now if I'm not mistaken.

**Comment by Lithrun** [comment]
Resolved as per https://github.com/AoTTG-2/AoTTG-2-Photon-Server/issues/6
