### ISSUE TITLE
License Update

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#240]
**How will this enhancement improve the game?**
Currently AoTTG2 is licensed under GPL3.0. However, this license does allow commercial usage of any AoTTG2 assets & work. Based on FengLee, this is not desired. Thereby, the GPL3.0 license needs to be replaced by a license similar to GPL3.0, but without commercial usage.

**Comment by sonicv6** [comment]
https://creativecommons.org/licenses/by-nc/3.0/

**Comment by sonicv6** [comment]
https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by Lithrun** [comment]
License is changed to https://creativecommons.org/licenses/by-nc-sa/4.0/
Nothing really changed, besides the fact that anyone using any of our source code, can no longer use it for any commercial usage.
