### ISSUE TITLE
Click to translate for In-game Chat Messages

### ISSUE THREAD

**Issue by winnpixie** [AoTTG-2/AoTTG-2#245]
**Is your feature request related to a problem? Please describe.**
I often find myself not understanding messages from Hispanic players, as I don't understand Hispanic languages, and only speak English.

**Describe the solution you'd like**
The ability to click on a message to automatically display a translated version.

**Describe alternatives you've considered**
Typing in their message in Google Translate. This is only okay for me when the message still uses English-esque characters, but other languages such as Russian or Japanese would not work well on a QWERTY keyboard.

**Additional context**
- [ ] Rework chat so Sender and Content are separate strings in a new Message object.
- [ ] Make chat messages clickable.
- [x] Write a function that sends an HTTPS request to Google Translate and parses the JSON response.

**Comment by Lithrun** [comment]
Looking forward to your Pull Request
