### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#247]
**Is your enhancement request related to a problem? Please describe.**
When pressing a single button, the game should take a screenshot. This screenshot is then automatically saved within a folder. Currently players rely on their own screenshot software, and having it implemented within the game would be a nice enhancement

**Describe the solution you'd like**
- [x] Introduce a new keybinding named "Screenshot" under the UI rebinds category. The default keybinding for this should be "F12".
- [x] Upon taking a screenshot, the game will automatically create a folder inside the "Screenshots" folder. This folder is a timestamp of the day month year. [The users culture settings **must** be respected  is based on the users culture day month year syntax.](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tostring?view=netframework-4.6.2).
- [x] The screenshot is named with the date and time of the user and saved as a png

The user pressed F12. The game will create a folder inside the "Screenshots" folder named "26-08-2020", and name the file "26082020_225432.png"

**Comment by FAStre** [comment]
Having some trouble with rebinds, Ive added some lines to InputManager.cs and InputUi.cs, but I get an error when adding the "Screenshot rebind", in the unity editor the error message reads:
Assets.Scripts.UI.Input.InputManager.KeyDown (Assets.Scripts.UI.Input.InputUi input) (at Assets/Scripts/UI/Input/InputManager.cs:350)
UIInputHandler.Update () (at Assets/Scripts/UI/UIInputHandler.cs:15)

For now Ive commented out the rebinds code.

**Comment by FAStre** [comment]
Unassigning myself due to time constraints and only being able to focus on #113 , if any dev takes this over I am free to give a quick rundown of what has been completed and what still needs to be worked on.
