### ISSUE TITLE
[BUG] Death Camera & Spec Mode mouse not working

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#253]
**Describe the bug**
When the player dies or goes within specator mode, they can view other players and navigate across the map. The movement keys (WASD) are working, but the player cannot use their mouse to change the view direction. Additionally pressing right click freezes the movement keys as well, this is also unintended.

**To Reproduce**
1. Host any lobby (Singleplayer or Multiplayer)
2. Die or enter spec mode (/specmode)
3. The mouse cannot be used to look freely.

**Expected behavior**
It is expected that players can freely look around while they are dead, and that pressing right click will no longer freeze the camera.

**Comment by FAStre** [comment]
Ive tried numerous MouseLook scripts and I always get the following error in the unity editor :

NullReferenceException: Object reference not set to an instance of an object
IN_GAME_MAIN_CAMERA.setSpectorMode (System.Boolean val) (at Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs:249)
FengGameManagerMKII.EnterSpecMode (System.Boolean enter) (at Assets/Scripts/FengGameManagerMKII.cs:832)
ChatCommandHandler.ToggleSpecMode () (at Assets/Scripts/Room/Chat/ChatCommandHandler.cs:261)
ChatCommandHandler.CommandHandler (System.String chatCommand) (at Assets/Scripts/Room/Chat/ChatCommandHandler.cs:598)
InRoomChat.CommandHandler (System.String input) (at Assets/Scripts/Room/Chat/InRoomChat.cs:151)
InRoomChat.HandleChatInput (InRoomChat chat) (at Assets/Scripts/Room/Chat/InRoomChat.cs:111)
InRoomChat.Update () (at Assets/Scripts/Room/Chat/InRoomChat.cs:31)

Adding the MouseLook script and calling it also causes WASD movement to no longer work either. Not sure how to proceed.

**Comment by Lithrun** [comment]
> 
> 
> Ive tried numerous MouseLook scripts and I always get the following error in the unity editor :
> 
> NullReferenceException: Object reference not set to an instance of an object
> IN_GAME_MAIN_CAMERA.setSpectorMode (System.Boolean val) (at Assets/Scripts/UI/Camera/IN_GAME_MAIN_CAMERA.cs:249)
> FengGameManagerMKII.EnterSpecMode (System.Boolean enter) (at Assets/Scripts/FengGameManagerMKII.cs:832)
> ChatCommandHandler.ToggleSpecMode () (at Assets/Scripts/Room/Chat/ChatCommandHandler.cs:261)
> ChatCommandHandler.CommandHandler (System.String chatCommand) (at Assets/Scripts/Room/Chat/ChatCommandHandler.cs:598)
> InRoomChat.CommandHandler (System.String input) (at Assets/Scripts/Room/Chat/InRoomChat.cs:151)
> InRoomChat.HandleChatInput (InRoomChat chat) (at Assets/Scripts/Room/Chat/InRoomChat.cs:111)
> InRoomChat.Update () (at Assets/Scripts/Room/Chat/InRoomChat.cs:31)
> 
> Adding the MouseLook script and calling it also causes WASD movement to no longer work either. Not sure how to proceed.

NullReference resolved as per https://github.com/AoTTG-2/AoTTG-2/commit/9af289fc34023be6cbb4b9642f114604d38f1c92

Issue was caused by 2 things:
- The MouseLook component was missing from the prefab. The prefab that is used is called `MainCamera_Mono.prefab`. You might have tried to apply this component to the MainCamera object in the AoTTG2 unity scene, yet that one is replaced by the prefab when you join a room.
- The MouseLook component could not be added to any gameobject, due to the fact that your class was named SmoothMouseLook, whereas the file was named MouseLook. Unity requires that these two are the same, as otherwise it cannot be found as a component.

Renaming SmoothMouseLook allows the component to be addable to other gameobjects. Adding it to MainCamera_Mono.prefab resolves the nullreference. The MouseLook does influence the existing camera currently, as it needs to be turned off by default, but I believe that you can solve that yourself 👍

**Comment by FAStre** [comment]
Most things are now fixed, just that /specmode doesnt work in the racing gamemode. You cant enter specmode, but shortly thereafter you are forced out and respawned. See Kinsoy's report: https://discord.com/channels/681641241125060652/709714243749937152/752181177246548070
just point number 1 is still unresolved.

**Comment by FAStre** [comment]
Last-Last issue is now the Spawn Menu toggle. Ive added a SpawnMenuToggle() method, but it doesnt seem to be working correctly as once the spawn menu is opened in specmode, presing Item1 again doesnt get picked up by the necessary if loop. I thought that maybe putting a void update() inside would work but unfortunately you cant. Ive added a few Debug.Log() messages to assist with debugging, but im unable to proceed.
