### ISSUE TITLE
[BUG] Racing Rings colliders

### ISSUE THREAD

**Issue by brenocogu** [AoTTG-2/AoTTG-2#270]
**Describe the bug**
Racing rings doesn't appear to have collisions on some sides

**To Reproduce**
1. Go to any racing level and find a "Racing Ring"
2. Try to stand on top of it (climb it, hook it, etc)
3. At some point you will be swallowed by the ring.

**Expected behavior**
The ring would not allow players to fall into it, neither trap them as they fall.

**Screenshots**
There's a gif (very zoomed) when I got trapped on a ring
![giffo](https://user-images.githubusercontent.com/43767387/92661355-d80ce880-f2d2-11ea-8a70-0c712fe02d61.gif)

**Additional context**
I've tested only on the Tiny City map, but this bug may appear on others maps as well

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
For the dev who will pickup this issue:
Investigate the "RacingObjective" prefab, and check it's colliders.
