### ISSUE TITLE
[BUG] Non-MC can change the level locally for themselves

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#275]
**Describe the bug**
When a non-MC attempts to change the level, upon the next restart, this level is changed locally for them. This is undesired behavior and only the MC can determine which levels are loaded.

**To Reproduce**
1. Host a lobby a MC and join with a non-MC client
2. As non-MC, go to Game Settings > Server Settings, choose a new level and select "Change"
3. As MC, type /restart
4. The level of the MC is not changed, but the level of the non-MC is not changed.

**Expected behavior**
If a player is not the master client, then they must respect the current level that is loaded and be prevented from loading other levels.

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Mi-Sad** [comment]
wait the step "4. The level of the MC is not changed, but the level of the non-MC is not changed." is confusing, does it load a new level in any client?
