### ISSUE TITLE
[3D Model Request] Headquarters

### ISSUE THREAD

**Issue by roxnsteady** [AoTTG-2/AoTTG-2#287]
**Information**
An Art Team creation. 

- [x] Model (3D Artists)
- [x] UV Map (3D Artists)
- [x] Adjust texture to fit game's style (2D Artists)

**Why is this 3D Model needed?**
Headquarters is needed for one of the maps created by the Mapping Team.

**References**
![image](https://user-images.githubusercontent.com/70555862/93658394-c7e0d000-fa6d-11ea-9bcc-78c52e2bad44.png)
From Sir_Teetan/meecube

For reference (2D Artists):
![HQ_Ref](https://user-images.githubusercontent.com/70555862/93658416-0080a980-fa6e-11ea-8cb0-d135c1542d0b.png)

**Files**
![HQ_UV](https://user-images.githubusercontent.com/70555862/93658417-024a6d00-fa6e-11ea-862b-56b780e2e9ad.png)
![hqregular](https://user-images.githubusercontent.com/70555862/93658419-02e30380-fa6e-11ea-8e51-dfec49d5d9f7.png)

**Comment by roxnsteady** [comment]
Needs retexturing from the 2D Artist Team.

**Comment by roxnsteady** [comment]
![image](https://user-images.githubusercontent.com/70555862/94328591-5e6d3e00-ffe6-11ea-913c-c0e906cc8e15.png)
Screenshot for the 3D Model.

**Comment by PoleDark** [comment]
Hello, any update regarding the texture?

**Comment by KoroSensei0320** [comment]
> Hello, any update regarding the texture?

Tony is working on it starting now.

**Comment by atirutw** [comment]
I'm no 3D or 2D artist but I hope the final texture will be PBR :)
