### ISSUE TITLE
Traitor Among Us

### ISSUE THREAD

**Issue by Prolonpo** [AoTTG-2/AoTTG-2#300]
**How will this feature improve the game?**
This will add a new gamemode into the game where players would need to utilize a different set of strategies in order to reach their objectives.

**Describe the solution you'd like**

(Part 1 of 4)

There is going to be a group of players and two of them are going to “shifters”

Players would need to go around the town in order to complete certain objectives
• Interact with tasks
• Perform observation
• Maintain wall cannon
• Purchasing food from NPCs
• Transporting stuff from a warehouse to barrack
• etc.

NPCs will also be roaming the town and some need to be interacted with in order to complete certain tasks.

Shifter players also have a set number of tasks, but their tasks are to sabotage the logistic of the soldiers
• Spill over crates of supplies
• Stuff a cannon full of cannon balls so that it is unusable
• Tinker with the resupply station so that it cannot be used (no more glowing white dot indicating that it can be used)

After 30 seconds, the sabotaged items will display a visual notification for all players.
• All sabotaged items will be fixable where players would need to complete skill checks
• Multiple players can collaborate on this in order to complete the progression bar

(Part 2 of 4)

Shifter players would have the ability to spread a “perfume” containing their spinal cord fluid.
• This will not turn the NPC into a titan immediately. However, the NPC affected by the perfume will now say that “ [player name] has spread this weird perfume that smells like flesh and rotten eggs ” when interacting with players
• NPCs will only turn into titans when the shifter players scream
• There will be a cooldown to the ability to spread the perfume – 30 seconds
• There will be a cooldown for the ability to scream – 60 seconds
• Due to the strenuous nature of the screaming and turning NPC into titans, the shifter player’s avatar will display sweat dripping from their avatar for 10 seconds
• This will be an indication that they are the shifter as no soldier player has the ability to scream

When screaming, all players will hear the scream, then lightning bolts indicating titan appearance will be shown.

All players would need to stop their tasks and head towards the titan’s location. There could be no titan, one titan, or many titans.
• Those NPC titans will be going around town and eating all other human NPCs and players.

After each “wave” of titans is cleared, the players will be able to hold a vote on who they think is the shifters. The player with the most amount of vote will be put under a firing squad.
• If the soldier is a normal soldier, they will get shot, twitch, and die
• If the soldier is a shifter, they will get shot, twitch, and start glowing

(Part 3 of 4)

In the case that the shifter player has been snuffed out, they will turn into a titan and cause a shockwave blast to propel all other players away and into the air.
• The shifter player will remain in this titan form, the goal now is to rampage through the map and to kill as many NPCs and soldier player as possible
• One slap and one kick is enough to kill the NPCs and the Soldier players in this case
• Watch out! If the shifter player hits the other shifter player, the second shifter player will also turn into their titan form and now there is going to be two shifters running around and wreaking havoc
• One strike to the nape will be enough to kill this shifter player – either through the blade or through thunder spears
• Thunder spears will be able to destroy the limbs of the shifters’ as well as the titans’
• If timed well, punches and attacks by shifters or the AI titans will be able to deflect the thunder spears – however, by doing so, the thunder spears will almost immediately explode after getting deflected, causing a shockwave which will push the shifter or the titan in a certain direction or even cause them to lose balance
• Shifter titans will also have the ability to strafe left or right in order to dodge incoming thunder spears or soldier players, this will have a 5 second cooldown

(Part 4 of 4)

The soldier players win if they are able to complete all of their tasks or snuff out the two shifter players.

The shifter players win if they are able to kill off all the NPCs in the map or that their number is equal to the number of remaining soldier players.

When a player dies, they will remain dead. However, they can keep “playing” as a ghost form of themselves invisible to alive players, but visible to dead players.
• Dead players will not be able to collide with living players, NPCs and titans; but will still collide with buildings, trees and other “hookable” assets
• Yes, dead players could harass one soldier player that is still alive by tagging along with him/her – in order to do the “can you see our dead comrades” vision

**Additional context** (Remove if not relevant)
I agree with Lithrun's judgement on this idea that it would be interesting, but not a very high priority element for now.

Here is the link to his comment on Discord: https://discord.com/channels/681641241125060652/683107211983323164/763828722447941683

**Comment by Lithrun** [comment]
Based on the proposal meeting:
-	Shifter can affect gameplay, different abilities for the shifter players
-	Not only limited to this gamemode, perhaps expanded into expeditions and other sections of the game
-	Need to try it out, in future implementation

**Comment by Prolonpo** [comment]
As a game mode similar to this can be created by allowing the players to tweak their settings or to assign a certain game mode with a preset setting, this proposal has been rejected after the Proposal Team's investigation.
