### ISSUE TITLE
Automatic Reconnection

### ISSUE THREAD

**Issue by Prolonpo** [AoTTG-2/AoTTG-2#308]
**How will this enhancement improve the game?**

This is an idea posted by @IRI on the Discord server. This will improve the game by allowing players who had crashed due to internet issues or to server failures to rejoin a game session whilst being at the same location as well as to have the same amount of data (kills, deaths, max damage, damage, etc.)

**Describe the solution you'd like**

In @IRI's words: The ability to reconnect to the game when the server is down.
If you quit the game due to a server failure, you can reconnect to the game and return to the game and your location and personal data will be preserved. 【Automatic reconnection】

**Additional context** (Remove if not relevant)

Original Comment from Discord (full credit goes to @IRI): https://discord.com/channels/681641241125060652/683376807101071489/765608695031529472

**Comment by Lithrun** [comment]
Should be fairly easy to implement: https://doc-api.photonengine.com/en/pun/v1/class_photon_network.html#ab7c39b4f0ec783b86b59cb2460332058

**Comment by Prolonpo** [comment]
Nice! Should I let @IRI know that his/her idea was accepted and that they have the option to join the Proposal Team's rank?
