### ISSUE TITLE
[BUG] Trost Is Completely Busted

### ISSUE THREAD

**Issue by DumplingDave** [AoTTG-2/AoTTG-2#315]
**Describe the bug**
Eren refuses to pick up the boulder and instead just smacks titans around the whole game

**To Reproduce**
1. Go to trost map
2. Notice Eren is running into the boulder for some reason

**Expected behavior**
Much like the show I expected Eren to try and save Humanity instead of just running into a boulder.

**Screenshots**
![trost bug](https://user-images.githubusercontent.com/73802301/97824197-49d93100-1c89-11eb-95c9-2514c2c88661.png)
![trost bug 2](https://user-images.githubusercontent.com/73802301/97824202-4d6cb800-1c89-11eb-9575-0af0f862bfa1.png)

**Log file**
[Player.log](https://github.com/AoTTG-2/AoTTG-2/files/5472477/Player.log)

**Additional context**
Nothing really to add just adding the issue because it hasn't been worked on yet to my knowledge and organization and stuff.

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
This is rather intentional to experiment with the new navigation pathfinding methods for Titans (NavMesh). Should be resolved in either #302 or #159.

Closing this issue.
