### ISSUE TITLE
[BUG]Female Titan doesn't play death animation

### ISSUE THREAD

**Issue by desu7** [AoTTG-2/AoTTG-2#316]
**Describe the bug**
When you fight and successfully kill Female Titan, she doesn't play the death animation where she starts to roar for about 15 seconds and call Titans in. Instead she stays still in the animation she was killed with (so if she was kneeling when dying she'll stay kneeled). This bug happens in both The Forest map and Outside the Walls.

**To Reproduce**
1. Go to The Forest - Classic map and choose "Annie" in the game mode. Alternatively go to Outside the Walls map and wait for Female Titan to spawn.
2. Defeat Female Titan.
3. She will stay still in the animation she was killed in and the following text appears in the console:
"NullReferenceException: Object reference not set to an instance of an object."

**Expected behavior**
Female Titan should play the dying animation and dissapear after some seconds, without any console errors showing up.

**Screenshots**
![Captura de pantalla (412)](https://user-images.githubusercontent.com/63552078/97866251-e3492700-1d0b-11eb-8eb8-7d291c7bb0ca.png)
![Captura de pantalla (415)](https://user-images.githubusercontent.com/63552078/97866301-fb20ab00-1d0b-11eb-86d9-0ecbe970d462.png)

**Log file**
[femaletitan.log](https://github.com/AoTTG-2/AoTTG-2/files/5474839/femaletitan.log)

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Acros5542** [comment]
She now plays the death animation, but the second phase of her fight (the additional titans spawning in) has not been implemented, since I'd _presume_ that's known because the error code in game indicates it's unfinished, I'll close this issue.
