### ISSUE TITLE
Promotional Poster (request)

### ISSUE THREAD

**Issue by KoroSensei0320** [AoTTG-2/AoTTG-2#332]
Create a promotional poster for advertising
**Preferred/suggested inclusions:**
- Titan with chopped off limb
- Captain Levi doing a pose in front of the titan
- Utgard Castle showing in background

These would be great as they set AoTTG 2 apart from the original - chopped off limbs is one of the most popular features, and Utgard Castle is the first new map to be included.

Levi will also have a "throw blade" skill in AoTTG 2, so you could include something like this if you'd like.

**Comment by KoroSensei0320** [comment]
Issue being worked on by ANJU H.S

**Comment by Prolonpo** [comment]
We can expand this to other assets such as cities, forest maps, and other sceneries which have so far appeared in the dev blog post.

Perhaps you could even make a poster with a squad of scouts (let's say 4 of them), facing all four cardinal directions, injured and exhausted but willing to fight until their last breath whilst surrounded by titans of all shapes and proportions? And with the current slogan (you can change it if you want): "All hope is not lost, fight with the AoTTG 2 development server"

Don't forget to include the AoTTG 2 logo in your work ANJU H.S! Looking forward to them!
