### ISSUE TITLE
Account Log-in via vk.com

### ISSUE THREAD

**Issue by Bobrokrot** [AoTTG-2/AoTTG-2#335]
**How will this feature improve the game?**
It will allow a majority of Russian-speaking community to easily register their account.

**Describe the solution you'd like**
I'd like an option to login into the game via vk.com. 

**Describe alternatives you've considered**
No alternatives were considered.

**Additional context** (Remove if not relevant)
vk.com is the largest social network in Russian-speaking countries. Our largest AoTTG community currently has 4300+ members (https://vk.com/aottg). You can find VK API here: https://vk.com/dev/manuals

**Contributor instructions** (Do not modify)
1. Determine if the feature is compatible with existing features and fits within the scope/design of the project
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by Lithrun** [comment]
Thank you for your proposal. Will investigate tonight on how to setup an oAuth2.0 for VK. Based on: https://github.com/autowp/oauth2-vk it appears to be possible 👍

**Comment by Lithrun** [comment]
Good news, setting up VK (Vkontakte) was very simple. So, AoTTG2 does support VK as a login method now! (So we currently support Discord, Google and VK. Twitter & Facebook will be added later...)

For any other IDP requests, you can have a look at this list: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers 👍
