### ISSUE TITLE
[BUG] /pause Message Staying Stuck on Screen

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#343]
**Describe the bug**
When you use /pause and then restart the game or switch servers without unpausing, the "Game Paused" message will remain on screen even though you're capable of moving around. This can be fixed by typing /pause again (which will clear the message but not pause the game), but if you cause this bug by switching to someone else's server, the message is stuck as you can't use /pause when not masterclient.

**To Reproduce**
1. Start a new lobby
2. Type /pause
3. Type /restart or leave the lobby and join a new one

**Expected behavior**
The "Game Paused" message should clear automatically when the game is restarted and not carry over to other servers.

**Video**
https://youtu.be/_XOsr_ym_TA

**Log file**
https://pastebin.com/M9zwj4Nr

**Additional context**
In AoTTG1, unpausing the game has a separate command /unpause, rather than just typing /pause again. This is a minor change so there's really no point in making AoTTG2 match it in my opinion, just figured I'd point out the difference.

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
This one should be fairly simple to resolve. What happens is that the `PauseService` does not reset itself whenever the round is restarted. Implement a new method inside the PauseService named `private void OnLevelWasLoaded(int level)`. OnLevelWasLoaded, as the name implies, gets called whenever a level is loaded. So, when the new restarted level is loaded, implement logic which sets the pausing to false.

**Comment by Acros5542** [comment]
I found an additional issue with this on multiplayer. If the MC types /pause, then restarts the game, despite the game not being paused if anyone else joins the server they will be frozen in their spawn locations with the "Game Paused" message on screen for them. I know there are some other ways to encounter this issue, but I haven't been able to consistently recreate it with any method other than by using this bug.
