### ISSUE TITLE
[BUG] Oversized Arm Hitboxes

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#348]
**Describe the bug**
The arm hitboxes on titans seem to either be oversized or reach too high, causing you to slice their arm at times when your blades realistically should never had touched them.

**To Reproduce**
1. Go on any map
2. Swing at nape or higher level of the titans
3. Stick 'em with the pointy end of your blades
4. Notice the times when the arm is sliced as well when it probably shouldn't have been

**Expected behavior**
Arm hitbox should more closely match where the model of the titan's arm is at.

**Video**
If you put it on 0.25x speed at around 11 seconds you can see it pretty clearly.
https://youtu.be/P-icg8C5iMc

**Additional context**
This is likely a lower priority bug since it doesn't affected gameplay that much.

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Zynku** [comment]
Need some clarification on this bug. I looked at the video you sent and the blades seem to only connect on the kill, hitting the nape. I don't see any connection with the titan arm hitbox.

**Comment by Acros5542** [comment]
> Need some clarification on this bug. I looked at the video you sent and the blades seem to only connect on the kill, hitting the nape. I don't see any connection with the titan arm hitbox.

Look at the titan's left arm immediately before I get the kill and after as he's falling to the ground.
It looks like I've only hit the nape, but I also struck the arm hitbox causing the limb to appear severed from the elbow down.
