### ISSUE TITLE
Move weapon logic from HERO.cs into abstract Weapon classes.

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#35]
_This issue is intended for Junior developers, as it involves basic code structure and structuring logic._

**How will this enhancement improve the game?**
We currently have an abstract class named "Weapon". Weapon should contain all logic which a weapon should have of a player. Currently all these values are stored within HERO, yet why should HERO know if it has 7 AHSS ammo left, if they only use blades? The weapon related logic from HERO class should be moved into Weapon. Do note, that weapon is an abstract class, and that each derived class must implement its methods. Currently reload logic is moved into Weapon, Blades and Ahss weapon classes, but there's still more work to do. Once this is setup, we can easily add thunder spears as thunder spears only needs to derive from the weapon class.

**Describe the solution you'd like**
No more weapon specific details should be within Hero class. A hero should only know that they have to reload their weapon as an example, the exact implementation details are managed within the derived classes. A weapon knows how to exactly reload, and how much ammo it has left.

**Implementation assistance:**
Within Hero class, check references of the following variables:
public bool useGun -> There's quite some references within Hero class like this: if (useGun) then do Ahss logic, else do blades logic. This can be moved within the weapon classes.
totalBladeNum, rightBulletLeft, hasRightBullet, leftBulletLeft, hasLeftBullet, currentBladeNum -> these are all related to the amount of blades / Ahss ammo you have left. Can also be moved.

If you need help, just ask! It's okay :+1:

- [ ] Move all Weapon related code from HERO into abstract weapon class, and ensure that blades and Ahss implement this.

**Comment by WayneZhenLi** [comment]
Maybe consider using the template pattern when dealing with how the weapon collider interacts with the weapon class.  I think weapons should all follow the same general process when used.

**Comment by WayneZhenLi** [comment]
Here's what I mean in more detail.  Currently the weapon collider for both blade and AHSS use a variable called active_me to determine when hitboxes are hit.  Currently both the blade and AHSS determine when to set and unset active_me separately in a reasonably complex set of logic.  But my opinion is weapons should work in general the same.  When attacking set active_me and when the animation ends unset active_me (it's more complicated than that but regardless the process should still be similar between weapons).

So I think that weapon classes should call functions from an abstract template class that various different weapon collider classes implement.

See template pattern:
https://www.geeksforgeeks.org/template-method-design-pattern/

**Comment by Lithrun** [comment]
Issue closed as being worked on in #33
