### ISSUE TITLE
[BUG] No FPS cap on Main Menu

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#351]
**Describe the bug**
The main menu currently is using a very high amount of system resources because it does not have an FPS cap set in place.

**To Reproduce**
1. Launch AoTTG2 and sit on the main menu
2. Using some sort of FPS tracker (shadowplay has one built in you can turn on), check the FPS the main menu is running at
3. Additionally you can use task manager to see it's using a very high amount of system resources

**Expected behavior**
Main menu should have an FPS cap so simply leaving the game up and idling isn't overly stressing your system.

**Screenshots**
(on a 2080TI graphics card)
https://cdn.discordapp.com/attachments/709670139276165152/783941096870248478/Screenshot_161.png
https://cdn.discordapp.com/attachments/709670139276165152/783946866227544074/Screenshot_277.png

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
Resolving this is fairly simply as well. When the main menu is opened, set the FPS limit to the refresh rate (Hz) of the monitor. https://docs.unity3d.com/ScriptReference/Application-targetFrameRate.html

Once the player goes in-game, the FPS limit should respect the users settings.
