### ISSUE TITLE
[BUG] FPS limit does not persist when changing lobbies

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#352]
**Describe the bug**
Regardless of what your setting is for an FPS limit in game, the first server you make when launching the game will always have an FPS limit tied to your refresh rate. Then, for all games you join after this first lobby, the FPS limit is uncapped. You can still cap the FPS limit for a specific lobby by setting the FPS limiter option to something after joining the lobby, but once you leave and join another lobby, the FPS will become uncapped again.

**To Reproduce**
1. Launch the game and join/create a server
2. Check the FPS
3. Leave the server and join/create a new one
4. Check the FPS again
5. Set an FPS cap using the FPS limiter option
6. Leave the lobby and join a new one
7. Check the FPS one last time

**Expected behavior**
The FPS limit option should persist when set, and if left empty, the first game you join when launching the game should have an uncapped FPS limit.

**Video**
https://youtu.be/yNCFzDl6rjs

**Log file**
https://www.dropbox.com/s/bxrgwiguh7km41a/FPS%20limit.txt?dl=0

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
Might be related to either: #351 or #344

**Comment by Rekperion** [comment]
The fix I have up resolves this when it goes through. Won't let me link this issue to my pull for some reason tho.
Edit: It let me link it now :)

**Comment by Rekperion** [comment]
Not stale. Just waiting. Should be all good soon!

**Comment by Rekperion** [comment]
Just waiting for another review for PR #474
