### ISSUE TITLE
[BUG] Utgard Castle Out of Bounds

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#355]
**Describe the bug**
Utgard Castle has two actual sets of barriers that surround the map - an innermost set of barriers that act as the farthest the player can go (which I'll refer to as the player barriers), and an outermost set of barriers that act as the actual set of invisible walls surrounding the map (which I'll refer to as the map barriers).
 
The map barriers actually have collision with your hooks, and on some parts of the map, the player barriers are close enough to it that your hooks can reach them. Especially on the eastern side of the map (assuming you spawn facing north) where the physical stone walls are, as on parts of this section either the player barrier is actually farther back than the map barrier or it is missing altogether.
 
By climbing up the invisible wall of the map barriers, or by gaining a bunch of height through other means (I managed to do it a few times using the speed glitch I reported), you can eventually get high enough to hook the invisible wall acting as the skybox for the map barriers, effectively allowing you to swing along the top of the map.
 
Additionally, the invisible wall functioning as the skybox of the player barriers doesn't seem to fully reach to the edges of space enclosed by the barriers on the ground, meaning it's possible to land on top of this lower skybox and skate along the roof of the map.

**To Reproduce**
1. Make a game on Utgard Castle
2. Go to the the walls on the far right/east of the map
3. Use your 3DMG to climb up the invisible wall until you're very high up
4. While high enough up, use your gas to drift towards the center of the map
5. You should land on the player barriers' skybox if you climbed high enough

**Expected behavior**
The map barriers shouldn't be reachable/hookable by the player and you shouldn't be able to get on top of the player barrier's skybox.

**Video**
https://youtu.be/A5muMgk1Ebc

**Additional context**
You can also hook the map barriers on Outside the Walls and Akina Racing (although you must first clip out of bounds on Akina).
To quote antigasp on this bug "As for Outside The Walls, that stuff is an old bug maintained from RC.  The outer set of barriers actually exists in all maps, and is required for hooks to work properly; Utgard just needs to be placed more carefully within the box, and have more invisible walls."

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
To fix:
- [ ] Change the layer of the colliders (Assets/Scene/scene/Utgard, gameobjectOutside) to "Default". This means that they do have colliders, but are not hookable
- [ ] Move the colliders slightly to prevent what happened in the video
