### ISSUE TITLE
New Setting: Gravity

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#363]
**How will this feature improve the game?**
With the new setting "Gravity", a master client can set the gravity level which applies to all players.

**Describe the solution you'd like**
Introduction of a new settings class called "GlobalSettings". This GlobalSettings class contains a property called "Gravity". This property must be of type "float?" (Nullable float). It should act as a multiplayer based on the default AoTTG2 gravity level. Where 1.0 is default, 0.0 would be no gravity and 2.0 would be double the gravity (ect.).

- [ ] Implement gravity (https://docs.unity3d.com/ScriptReference/Physics-gravity.html)
- [ ] Implement GlobalSettings class (Assets.Scripts.Settings)
- [ ] Extend GameSettings to support GlobalSettings
- [ ] Extend SettingsService to support GlobalSettings (Add OnGlobalSettingsChanged(GlobalSettings settings) event)
- [ ] Subscribe to this event in the class where the gravity logic is executed, so whenever the MC updates the gravity, this is changed for everyone.

**Comment by Prolonpo** [comment]
This issue is also related to #323
