### ISSUE TITLE
[BUG] Kill Dmg not clearing from the screen

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#367]
**Describe the bug**
By leaving a single or multiplayer game while the yellow damage for a kill is still on screen (not just in the kill feed but the larger number that displays immediately after killing a titan), upon joining another lobby this damage number will be permanently stuck on screen. If you get another kill while in this state, this new number will replace the old one, but then it will not clear successfully itself. Closing the client and relaunching fixes this, /restart does not. (Also sorry for no video, since moving back home I don't have the upload speed to reasonably upload videos anymore, but I can go back and upload all needed footage relatively quickly in about a month from now - if footage is needed for anything let me know and I can get it uploaded in about 24-48 hours from then depending on how long of a clip.)

**To Reproduce**
1. Create a single or multiplayer lobby
2. Kill a titan and immediately leave the lobby before the dmg number leaves the screen
3. Create a new single or multiplayer lobby

**Expected behavior**
The kill damage should correctly clear from the screen and not persist when the game is restarted or left.

**Log file**
https://www.dropbox.com/s/vth5pnfl7h3x4vj/Dmg%20number%20bug.txt?dl=0

**Additional context**
This works on both Alpha 0.1 and Alpha 0.2

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
To resolve this, a similar approach as #343 can be applied. Whenever the user leaves the room, these UI elements should be destroyed
