### ISSUE TITLE
[BUG] Account Only Lobbies aren't account only

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#386]
**Describe the bug**
You're able to both create and join Account Only Lobbies without being logged in.

**To Reproduce**
1. Launch a new instance of AoTTG2 and without signing in, create an Account Only Lobby
2. Launch a second instance of AoTTG2 and try to join this Account Only Lobby without signing in (it may take one or two tries as it seems you're not always able to connect to any multiplayer server on the first try)

**Expected behavior**
Account Only Lobbies should only allow players who are logged in to join.

**Additional context**
Players who aren't logged in being able to create account only lobbies is not a bug, but something likely to be changed.
Lithrun's comment on it: "When implementing it, I did allow the creator to be a non-account player, but now thinking about it, would make sense to forbid them as well if they have no account"

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
This is rather an UX issue than a technical one. Users without an account are able to create an account-only lobby, but the Photon Server will check that if they are not logged in, it will not make the room account-only. So it might look like that you are able to create an account-only lobby, but in reality it is just a regular lobby.

**Comment by Acros5542** [comment]
Just tested this by making the lobby on a signed in client and trying to join on a non signed in client and you're absolutely right. I should have tested these two issues separately.

**Comment by Lithrun** [comment]
Will convert this into an Issue for the Photon Server, since I think that the "Account Only" icon doesn't get removed yet

**Comment by Lithrun** [comment]
Photon Server issue: https://github.com/AoTTG-2/AoTTG-2-Photon-Server/issues/8
Should be fixed shortly.

**Comment by Lithrun** [comment]
Issue from the Photon Server is done. No changes are required in this repo for that to work, so issue closed.

**Comment by Acros5542** [comment]
Since the change I have not been able to make an account only lobby at all, regardless of whether I'm logged in or not, the box will not be ticked when selected.

**Comment by Acros5542** [comment]
Follow up, what I reported above is not solely related to this issue, it seems any tick/toggle boxes in the game are no longer displaying the tick mark, so regardless of what setting they're on they appear to be toggled off. Will report as a separate issue in a minute.
