### ISSUE TITLE
[BUG] Player titans moving on death

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#389]
**Describe the bug**
If you suicide while moving as a player titan your model slides across the floor of the map until it despawns.

**To Reproduce**
1. Create a multiplayer lobby on forest
2. Spawn as a titan
3. Hold W
4. Suicide while still holding W

**Expected behavior**
Your model should fall and remain motionless after suiciding.

**Additional context**
I'm guessing this is because your speed isn't reset to 0 after suiciding, so your model continues to slide at the speed you were moving before suiciding.

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
PlayerTitan.FixedUpdate does not check whether or not the PlayerTitan is dead, which is causing above. Simply adding a check to determine if the titan is dead or not, will resolve above
