### ISSUE TITLE
[BUG] Female Titan doesn't spawn in Alpha 0.2's Forest Annie Gamemode

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#390]
**Describe the bug**
When trying to play on the Annie gamemode of Forest on Alpha 0.2, Annie doesn't spawn at all, instead skipping directly to the 10 titans after she has been beaten.

**To Reproduce**
1. Go to Forest and set the Annie gamemode
2. Start the game and spawn in

**Expected behavior**
One very angry female titan should be trying to kill me.

**Screenshots**
Already on the 10 titans phase of her fight despite just spawning and the server existing for only 6 seconds:
![Screenshot (363)](https://user-images.githubusercontent.com/75679898/102859164-7e4faa80-43f9-11eb-8ca2-11fe863c8273.png)

**Additional context**
Annie will still spawn on Outside the Walls if Checkpoint 5 is captured. This bug is new to Alpha 0.2, as she spawns normally on Alpha 0.1.
Credit to Kiefer for first discovering this.

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
Inside the "KillTitansGamemode" there is logic which will spawn the female titan (or rather, the logic which is supposed to spawn her...). From there you should be able to sort it out 👍
