### ISSUE TITLE
[BUG] Cursor issue

### ISSUE THREAD

**Issue by KoroSensei0320** [AoTTG-2/AoTTG-2#399]
**Describe the bug**
On Mac, "Alpha 2" (Edit: Till current, although recent builds are unable to open)
Upon reaching lobby creation screen (both single-player and multiplayer), the cursor disappears and the user is unable to interact with any buttons.
Furthermore, my Mac got quite heated and turned on its fans (fairly intensely).
I thought this may be due to the uncapped FPS on the menu, but as this heating/fans problem is unique to the later builds, this is unlikely to be the cause.

**To Reproduce**
Steps to reproduce the behaviour:
Mac only, tested on Catalina. Unable to confirm for earlier versions.
1. Go to 'Multiplayer'
2. Click on 'create room'
3. See error

**Expected behaviour**
The cursor is visible and can interact with buttons.

**Log file**
[Player.log](https://github.com/AoTTG-2/AoTTG-2/files/5733154/Player.log)

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Acros5542** [comment]
Any update on this? @Lithrun

**Comment by Lithrun** [comment]
None as we don't have any Mac developers available.

**Comment by dark3art** [comment]
Steps to open a Mac Build:
download the build and unzip it
add it into the Application folder
open the terminal
**_enter these command as following:_** 
(change AppName to the name of the application for example if the file reads AOTTG2.app --> sudo chmod -R 777 /Applications/AOTTG2.app)

sudo spctl --master-disable
sudo chmod -R 777 /Applications/(appName).app
xattr -d com.apple.quarantine /Applications/(appName).app
xattr -cr /Applications/(appName).app
