### ISSUE TITLE
[BUG] Spawning the Female Titan is giving some errors

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#40]
_This issue is intended for Junior Developers only!_
**A branch is already created. Please clone the branch with the same issue number.**

**Describe the bug**
Upon spawning the female titan, there are some errors. These errors are caused because of during the asset extraction, script references weren't present. Via code it is easy to backtrack which script reference is where, but gameobject references aren't there anymore either. Simplest way of solving this, is to simply spawn the female titan, see where errors occur, and then fix it.

Additionally, some animations aren't correctly configured. The asset export placed all animations within the same folder, these animations weren't overwritten, but file names with the same name, were appended by _X. The Female Titan script is looking for an idle animation, but the animation within her animations list is idle_1. Same applies for run, and perhaps more once those are resolved.

**To Reproduce**
1. Pull branch #40-female-titan
2. Spawn within the city (FT is automatically spawned, so you don't have to figure that out yourself 👍 

**Expected behavior**
It's expected that the female titan works without giving any errors in the output log.

**Additional hints**
You may want to move Female Titan specific animations within a new folder called: "Assets/AnimationClip/Titan/Female Titan" to prevent conflicting file names.

If you need help, feel free to ping any dev on discord channel #40.

- [x] Ensure that the right animations of the Female Titan are applied
- [ ] Resolve any additional errors that occur during testing
- [ ] Remove the hack that spawns the Female Titan (FengGameManagerMKII/OnLevelWasLoaded -> line 5055 & 5056)
- [ ] See the //HACK comments at ServerList.cs

**Comment by sonicv6** [comment]
Animations issues are resolved and all properly organised.
