### ISSUE TITLE
[PROPOSAL] Dummy Titan training 

### ISSUE THREAD

**Issue by Alex-Mod-Bot152** [AoTTG-2/AoTTG-2#403]
Idea by @Alex152
#8670

**How will this enhancement improve the game?**
A way for players to practice striking down titans. Making it a great way to train attack from different angles and position also on moving targets. Also it would be great use for dummy titans 

**Describe the solution you'd like**
Having dummy titans randomly placed around the training map, map would have other randomly places assets like trees, buildings and boulders etc. There would be time limit dictated my difficulty of the game. Easy having biggest amount of time and least amount of dummies (5 minutes and 3-8 dummies), Medium (3 minutes and 8-13 dummies), Hard and above (1 minute and 13-20 dummies). You could deal damage to those dummies in similar way you deal it to titans with numbers showing how much you did and objective is to deal as much damage as possible in the shortest amount of time. 

**Contributor instructions** (Do not modify)
1. Determine if the enhancement is compatible with existing features
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by Lithrun** [comment]
Sounds like a continuation of a new gamemode dedicated to #25 & but also related to the training gamemode #115

**Comment by Alex-Mod-Bot152** [comment]
> Sounds like a continuation of a new gamemode dedicated to #25 & but also related to the training gamemode #115

Now that I look into it you are right. This can be treated as continuation or expension to issue #25 and #115

**Comment by Prolonpo** [comment]
As dummy titan models have been created and there already has a game mode to strike them down, this seems that this issue overlaps their information.

Closing this to declutter the GitHub page.
