### ISSUE TITLE
[PROPOSAL] Hooks detaching from objects

### ISSUE THREAD

**Issue by Alex-Mod-Bot152** [AoTTG-2/AoTTG-2#409]
Idea by @spideyrobo312004

Reference post- https://discord.com/channels/681641241125060652/683376807101071489/790299419777564722 and more explanation https://discord.com/channels/681641241125060652/683107211983323164/791741287439138846

**How will this enhancement improve the game?**
A more challanging gameplay on Realistic Difficulty 

**Describe the solution you'd like**
If some criteria such as speed or time is met the hook would detach from object either them being walls or titans 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or ideas you've considered.

**Additional context** (Remove if not relevant)
Author idea: I was thinking for the realistic mode it would be not possible to swing long enough to gain speeds possible of reaching the top of the wall or above the wall and if we were able to be knocked off a wall with enough momentum then that could mean the titans could pull us off too because right now it seems like the only way for us to detach from an object is by being killed or by us willingly detaching and there is also the problem of how long we can hold onto things like I can hook onto a player titan and they could run across the map while I’m still hooked through a wall so maybe the wire should be cut off or bend at a point where the wire is interfering with the landscape.

**Contributor instructions** (Do not modify)
1. Determine if the enhancement is compatible with existing features
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by Prolonpo** [comment]
Staff discussion (start): https://discord.com/channels/681641241125060652/683483289289621515/796114267773337660

**Comment by Prolonpo** [comment]
Perhaps this idea should instead focus on a list of 3dmg compatible materials (if you hook on these materials, you can fly) and a list of 3dmg incompatible materials (if you hook on these materials, you can't fly as the hook doesn't anchor in those materials) that would impact the gameplay

https://discord.com/channels/681641241125060652/683483289289621515/796221512361181214 (staff chat)

**Comment by Prolonpo** [comment]
This proposal was present in the 3rd Proposal Meeting on Feb. 20, 2021.

This proposal was labelled as pending and future testing would be required to determine if this would be a viable system.

**Comment by Prolonpo** [comment]
This proposal, after investigation by the Proposal Team, was rejected for implementation into AoTTG2.
