### ISSUE TITLE
[PROPOSAL] Female looking titans

### ISSUE THREAD

**Issue by Alex-Mod-Bot152** [AoTTG-2/AoTTG-2#410]
Idea by @spideyrobo312004

Reference post-https://discord.com/channels/681641241125060652/683376807101071489/790300117386788865 and more explanation https://discord.com/channels/681641241125060652/683107211983323164/791741287439138846

**How will this enhancement improve the game?**
Players being able to get more immersed into the game

**Describe the solution you'd like**
Some titans would have more femine features like beady eyes, longer hair, being thinner or femine features like wider hips 

**Describe alternatives you've considered**
Adding more models to the titans

**Additional context** (Remove if not relevant)
Author comment: For the female looking titans I’m not entirely sure how you could make them look more feminine I’ve seen that most if not all the female titans are thin and never fat like the originally male human titans they usually always have longer hair and also I’ve seen some of the male looking titans from the show and some can be bald or have a beard would you consider adding more variety with the face also I even saw one with a mustache the eyes I don’t think matter as much.the smiling titan had beady eyes 

**Contributor instructions** (Do not modify)
1. Determine if the enhancement is compatible with existing features
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by Prolonpo** [comment]
Considering that Annie's Titan was nicknamed the Female Titan, this means that other titans had mostly male body types - and Annie's Titan was special due to its body type.

Thus this issue would be too much relevant in light of what the show offers.

Closing this issue due to the mentioned reasons.
