### ISSUE TITLE
[BUG] Camera Issue - Range of crosshair movement on different resolutions

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#423]
**Describe the bug**
On resolutions other than 1920x1080p, you're not always able to move your crosshair to the corners of the screen on Original or WoW camera types. AoTTG2 has a sort of limiting box that stops you from moving your crosshair out of the window when playing on Original or WoW camera types (thankfully, as this makes playing on these camera types with multiple monitors possible); however, this limiting box doesn't seem to be properly scaling with the game's resolution.

**To Reproduce**
1. Go to any map and spawn in
2. Switch to Original camera (default key is C)
3. Press backspace or change your resolution to something under 1920x1080p (more noticeable on lower resolutions)
4. Try to move your crosshair to the edge of the window

**Expected behavior**
Your crosshair should be able to reach the edge of the screen regardless of resolution when playing on Original or Wow camera types.

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
The fix of #422 also fixes this bug. Double ~~kill~~ bug fixes!
