### ISSUE TITLE
Command Line Interface (CLI)

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#43]
**Is your feature request related to a problem? Please describe.**
Chat room should just be for chat. For commands, there will be the CLI. From this CLI users can execute commands, and see a log of recent actions that occurred.

**Describe the solution you'd like**
A complete CLI

**Describe alternatives you've considered**
Outputting everything within RoomChat would making the chat too crowded. Thereby a CLI will suffice.

- [x] Investigate a proper way of managing commands. We don't want to end up with 1000+ line method like InRoomChat/ Report findings to @AoTTG-2/development-team on discord channel #43-cli.
- [x] Opening and closing the CLI can be done with the same key (Can be hardcoded for now, will be changed once new rebinding structure is setup)
- [x] Upon opening the CLI, you can directly start typing the command
- [x] Predictive commands

**Comment by TicExp** [comment]
I suggest a label that shows commands that start with your current input. Displayed info contains all information that you specified through code. New code architecture allows to implement that easily.
