### ISSUE TITLE
[BUG] Typing HTML styling into chat can cause some oddities

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#430]
**Describe the bug**
In both AoTTG1 and 2, the chat will accept certain stylings for text such as <color></color> or <size></size>; however, in AoTTG2 this form of styling while still executed behaves differently. Any changes to the text color will have no affect, as the text still is printed white. However with <size>, the text will instead be printed as a blank message, and an error code will be given in the chat for both this message, and all future messages sent in the chat, regardless of if they have been styled or not.

**To Reproduce**
1. Join or create a lobby
2. In the chat type <size=30>test</size>
3. After, send a normal message in the chat without any styling

**Expected behavior**
Either the chat should properly execute HTML styling or not execute it at all.

**Screenshots**
![Screenshot (379)](https://user-images.githubusercontent.com/75679898/103380680-a3a67d80-4ab7-11eb-9117-a17a21dff30a.png)

**Log file**
https://www.dropbox.com/s/treycx6va7hsna2/text%20styling.txt?dl=0

**Additional notes**
This one is a very minor issue, I only felt it worth reporting since it continued to give error codes in the developer console for future, non-styled messages.

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Toorah** [comment]
I suppose it should be decided whether or not to allow or block html tags in chat.
Personally I'd vote to block them, for various reasons, including consistency
