### ISSUE TITLE
[BUG] Aim cursor and actual curser does not line up

### ISSUE THREAD

**Issue by atirutw** [AoTTG-2/AoTTG-2#448]
**Describe the bug**
This screenshot pretty much describes what's going on.
![image](https://user-images.githubusercontent.com/25323231/103763212-1bdae900-504c-11eb-9150-7524a63192b2.png)
Also because that the game raycasts to the mouse position instead of the curser, the gameplay also took a big blow from this bug.

**To Reproduce**
Start a singleplayer match(prob occurs on multiplayer too), that's it. The actual cursor is not lining up with the aim cursor

**Expected behavior**
The aim cursor should line up with the actual mouse position.

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
Isn't this the same as #422?

**Comment by atirutw** [comment]
> Isn't this the same as #422?

Definitely the same one. Let's close this one down

**Comment by Lithrun** [comment]
Alright then. This issue is closed due to being identical to #422
