### ISSUE TITLE
[PROPOSAL] Ways to save teammates - Cooperative and ideas

### ISSUE THREAD

**Issue by EdJairRodriguez** [AoTTG-2/AoTTG-2#451]
**How will this feature improve the game?**
it could make it less stress and more cooperative playing in abnormal difficulty or hard

**Describe the solution you'd like**
i've thought in 3 things to add:
1) save yourself: by the cost of brake 2 blades + 20% of total gas, you can use the levi's ability in the opposite direction where the titan is looking cutting her fingers and make the titan unable to grab for 5 secs. you can add white smoke particle in her hand in signal that is regenerating (titan can still punching humans while is regenerating too).
![descargar](https://user-images.githubusercontent.com/34397155/103809452-d0c7d280-5059-11eb-982c-d35e3cb0f70a.png)
2) save teammate: by the cost of 2 blades you can throw your blades to the titan's eyes.
- you can add a sphere collider from the titan's eyes if the player goes inside activate the trigger
![image](https://user-images.githubusercontent.com/34397155/103811017-7ed47c00-505c-11eb-91c5-3e8f74b7f697.png)
what trigger should do:
- if player press "whatever button" auto aim and throw his blades (camera focus enemy eyes + player animation throwing blades).
- titan leave the player (if someone is grabbed) and start the animation when get her eyes damaged(already exists in the original game) only adding the typical white smoke in signal that is already regenerating.
![image](https://user-images.githubusercontent.com/34397155/103813178-f22bbd00-505f-11eb-8b88-ba3d824be377.png)
3) titan's blood effect:
- human side: it should depend of how many times player's blades connect with titan's body in x seconds (same as stylish bar) adding blood and the particle effect of the white smoke at random parts of the player body. 
![image](https://user-images.githubusercontent.com/34397155/103814426-efca6280-5061-11eb-8057-5e4cb81c38f3.png)
-titan side: im not sure if it possible to get the direction of the player's blades when connect with titan but if it's possible it should be great add a scar (and rotate the image depending of the cut) and add particle effect of white smoke by 5 secs for example and add the sound when titan is regenerating.
![image](https://user-images.githubusercontent.com/34397155/103816955-19858880-5066-11eb-9668-2ffa271d1fbe.png)
![image](https://user-images.githubusercontent.com/34397155/103816449-484f2f00-5065-11eb-8a8a-a20615c74127.png)

if you want to contact with me to talk this points, use discord: EddyR#0182 
or twitter: @EddyR261
thx

**Describe alternatives you've considered**
N/A

**Contributor instructions** (Do not modify)
1. Determine if the feature is compatible with existing features and fits within the scope/design of the project
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by atirutw** [comment]
I really like this idea but throwing your blades into their eyes is a bit much. 
*shrugs*

**Comment by Prolonpo** [comment]
Issue #630 presents findings from the Proposal Team's investigation on more ways to save a player

**Comment by Prolonpo** [comment]
In terms of the first point on using blade and gas to escape, this would make Jean Skill obsolete, which would not likely be appreciated.

For the second point on the ability to throw blades, this ability would already have been approved for implementation as a skill.

For the third point on blood effect and scars on titan, this would definitely play a nice visual effect.

**Comment by Prolonpo** [comment]
Putting a request to close this issue.

**Comment by Prolonpo** [comment]
Issue closed after the Proposal Team rejected this proposal.

**Comment by atirutw** [comment]
:cry:
