### ISSUE TITLE
[BUG] High menu CPU Usage

### ISSUE THREAD

**Issue by atirutw** [AoTTG-2/AoTTG-2#457]
**Describe the bug**
The CPU usage is unusually high in the menu(it's also high while in a game but it's a lot less severe).
Please note that I have not tested this in a build yet

**To Reproduce**
1. Open Task Manager
2. Navigate to the Performance tab
3. Start the game
4. The CPU Usage goes up significantly
5. Start a game on any map
6. The CPU drops to about half of the menu usage.

**Expected behavior**
The CPU usage should not be that high.

**Screenshots**
This is my baseline CPU usage:
![image](https://user-images.githubusercontent.com/25323231/104119181-65834680-5360-11eb-9346-c994d68f2ded.png)

This is while in the menu:
![image](https://user-images.githubusercontent.com/25323231/104119214-906d9a80-5360-11eb-98a0-5c60f6cd2d7b.png)

And this is while in a game:
![image](https://user-images.githubusercontent.com/25323231/104119328-1f7ab280-5361-11eb-8b7c-c682c63fb30b.png)

**Log file**
Include a log file

**Additional context**
This is a big performance issue considering that my CPU have a moderate horsepower and the menu still takes up about 50% of the CPU. I can imagine this being an even bigger problem on a weaker CPU.

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
Identical to #351
