### ISSUE TITLE
[BUG] Titan Health is no longer visible on Alpha 2.1

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#461]
**Describe the bug**
Pretty simple, seems titan health numbers don't appear anymore on the 2.1 Alpha build. Note they were appearing properly on Alpha 2.0

**To Reproduce**
1. Go to any gamemode with Titan Health (Forest Realism difficulty for example, or the Female Titan fight)
2. Spawn in as a human
3. Look at the empty air above the titans' heads menacingly

**Expected behavior**
Titan health should be visible on gamemodes in which health mode is turned on.

**Screenshots**
Annie with no health: ![Screenshot (407)](https://user-images.githubusercontent.com/75679898/104146523-11e11f00-5399-11eb-9447-4612b28fd49c.png)

**Log file**
https://www.dropbox.com/s/hn8dotu37upjpm8/No%20health%202.1.txt?dl=0

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
This appears to be broken as per #430 (PR #449). Changing the font to Dynamic does work for the chat, but it appears to be incompatible with the Health Labels. So either:
1. Refactor the Health label to be compatible with Dynamic fonts
2. Add a static font which health labels can use

**Comment by atirutw** [comment]
I upvote refactoring the code.

**Comment by Acros5542** [comment]
Fixed and never closed.
