### ISSUE TITLE
[BUG] FPS Limiter no longer works - Alpha 2.1

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#462]
**Describe the bug**
Seems since v-sync has temporarily become something that is always on, it's taking priority over the FPS Limiter option, so no matter what you put in for the FPS Limiter, your FPS will still be locked to your monitor's refresh rate.

**To Reproduce**
1. Go into any game
2. Open the menu with escape and under graphics settings set a number for the FPS Limiter and hit save
3. Notice the FPS cap doesn't change

**Expected behavior**
Actually, this is sort of behaving how it should - normally in AoTTG if both V-sync and an FPS limit are set, V-sync will take priority. However, right now as V-sync is permanently on this prevents setting an FPS limit at all.

**Additional context**
Right now I see this as extremely low priority, as once V-sync becomes a toggleable option again it will effectively have to be reverted to once again match RC. Unless it's a problem for specific testers with hardware limitations, this one imo isn't worth fixing, just figured I'd make it known.

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Rekperion** [comment]
I swear it not stale. Just waiting for review. My PR fixes this issue as well as #352

**Comment by Lithrun** [comment]
Will schedule the review for tomorrow 👍

**Comment by Rekperion** [comment]
Just waiting for another review for PR #474
