### ISSUE TITLE
[PROPOSAL] New Gamemode - Escort/Protect Civilians 

### ISSUE THREAD

**Issue by Alex-Mod-Bot152** [AoTTG-2/AoTTG-2#484]
Idea by @Bakayarou

Reference post-https://discord.com/channels/681641241125060652/683376807101071489/801207373020659743

**How will this enhancement improve the game?**
New gamemode for players to enjoy 

**Describe the solution you'd like**
Using custom logic so that titans try to get to civilians and eat them. We have to either kill all the titans or Escort all civilians to safety

**Additional context** (Bakayarou original idea)
Idea for game mode : protect the citizens name (tbc). basically titans get in the city and you have to kill the titans while making sure the citizens get evacuated safely. two ways you can win/ lose : to win either kill all titans, or see that a certain amount/% of citizens gets evacuated safely. to lose, either the titans eat too many citizens or the soldiers get eaten or the capture the evacuation point. the citizens could either be ai player characters or 1-2m titans with the path AI to go to the evacuation zone which could be a checkpoint, upon entering said checkpoint, they despawn and get counted towards a meter.

**Contributor instructions** (Do not modify)
1. Determine if the enhancement is compatible with existing features
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by Lithrun** [comment]
Sounds nice, but identical to #110
