### ISSUE TITLE
[BUG] Minimap no longer displaying the ground after reaching a certain height

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#501]
**Describe the bug**
Possibly related to #429, or could at least be fixed at the same time. Basically, when the minimap adjusts its display of the map, it factors in the player/camera height; however, if you go too high on some maps, the minimaps display of the map un-renders the map and turns entirely black.

**To Reproduce**
1. Go to City (probably the easiest map to do it on)
2. Launch yourself to the skybox
3. Look at the minimap as you reach it and fall back down

**Expected behavior**
The minimap should correctly render the map regardless of height.

**Screenshots**
![Screenshot (512)](https://user-images.githubusercontent.com/75679898/106371924-693f3300-6338-11eb-9be5-337a9d82f8e0.png)

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by DaSquyd** [comment]
I'll fix this alongside #429
