### ISSUE TITLE
[BUG] The icons for remaining blades on the HUD do not scale properly with resolution.

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#522]
**Describe the bug**
When launching the game, what resolution setting you're on determines how spread out or close together the blade icons are on the HUD. This spacing for the icons will then persist even if you change the resolution while playing.

**To Reproduce**
1. Launch the game and go to any map
2. Spawn in as a human and notice the spacing of your blade icons on the HUD
2. Press escape and go to Graphic Settings
3. Change your resolution to something different than what you're currently on (easiest to notice on 640x480p)
4. Close out of the game
5. Relaunch AoTTG2
6. Go to any map and spawn in as a human
7. Notice the spacing of your blade icons
8. Change your resolution back to what it had been previously
9. Notice that the blade icon spacing did not change

**Expected behavior**
The spacing for the blade icons on the HUD should scale properly with resolution.

**Screenshots**
Normal spacing on 1920x1080p:
![Screenshot (536)](https://user-images.githubusercontent.com/75679898/106428559-2dd75e00-6437-11eb-9b1f-0a7a89d99507.png)

Spacing on 640x480p after relaunching the game:
![Screenshot (537)](https://user-images.githubusercontent.com/75679898/106428705-65460a80-6437-11eb-8bee-e93c01230262.png)

Spacing on 1920x1080p upon switching back to it after having launched on 640x480p:
![Screenshot (538)](https://user-images.githubusercontent.com/75679898/106428810-8a3a7d80-6437-11eb-8ab7-d65a0737737d.png)

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by gisketch** [comment]
Will fix this along with issue #537
