### ISSUE TITLE
[BUG] Upside down camera on the Original camera type.

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#524]
**Describe the bug**
This is a known issue, but I noticed it doesn't have an official bug report yet so here it is. It is possible to flip your camera completely upside down on the Original camera type whilst tabbed out of the game. This is due to the fact the camera still moves even when the game is minimized or your cursor is outside of the game window.

**To Reproduce**
1. Go to any map and spawn in
2. Set your camera type to Original (you can cycle camera types with C)
3. Press Alt + Tab, then let go of Tab but continue to hold Alt
4. Move your cursor around a bunch until you see the camera flip upside down.
5. Tab back into the game.

**Expected behavior**
The camera should not flip upside down.

**Screenshots**
![Screenshot (539)](https://user-images.githubusercontent.com/75679898/106439807-1d7aaf80-6446-11eb-852c-9eee607bd76d.png)

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by SaudBako** [comment]
I couldn't reproduce the exact bug, but I'll work on stopping all camera movements when the game loses focus.
This flipping did happen on TPS by the way, but without without even tabbing out of the game window, which might require a github issue on its own.
