### ISSUE TITLE
[PROPOSAL] Upgrade to Universal Render Pipeline

### ISSUE THREAD

**Issue by atirutw** [AoTTG-2/AoTTG-2#526]
**How will this enhancement improve the game?**
This will bring many SRP features(shader graph, etc.), enhancement, and fixes the problems we are currently having with the deprecated built-in RP(flickering terrains, etc,)

**Describe the solution you'd like**
1. Install Universal Render Pipeline
2. Upgrade materials in the project to use the URP shaders
3. Port custom shaders to URP

**Describe alternatives you've considered**
*Graphics*:
+ Using Amplify Shader Editor or just write one from scratch is very fine (but we still need to move to either URP or HDRP for the problems we're having)

*Fixes for the terrain flickering*:
1. Adjusting Near/Far clip of the camera.
Result: not very reliable. These methods only make the flickering less intense/noticeable. A high Near Clip value also clip out things that are too close to the camera.
1. Adjusting shadow bias.
Result: same as Near/Far clip method but make the shadows less accurate.

**Additional context** (Remove if not relevant)
This is a project I made to confirm if the flickering problem is gone.  Since this is a universal problem, any projects using built-in RP will suffer from it when terrains are far away from the scene's center. As you can see, URP have no flickering whatsoever even at 20 km away from the center. 

https://user-images.githubusercontent.com/25323231/106578035-ab06ee00-6571-11eb-9ec3-b61b150ff290.mp4

**Contributor instructions** (Do not modify)
1. Determine if the enhancement is compatible with existing features
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by FAStre** [comment]
Can we consider this closed on #340 merge?

**Comment by Lithrun** [comment]
Yup, #113 (PR #340) contains it, so will add the Closes keyword to it 👍
