### ISSUE TITLE
[BUG]Horse stuck in a loop trying to follow the player

### ISSUE THREAD

**Issue by merinobruno** [AoTTG-2/AoTTG-2#529]
**Describe the bug**
When you get far away from the horse, it'll rush towards you. When it gets to your position, the inertia will make him go far away from you and it'll rush again towards you in a loop.

**To Reproduce**
1. Go to 'Outside the Walls'
2. Get far away from the horse
3. Scroll down to 'Wait for the horse to get to your position'
4. See the problem

**Expected behavior**
I think the horse should slow down the closer it is from the player.

**Screenshots**
![1](https://user-images.githubusercontent.com/54451815/106684228-d3f4a680-65a4-11eb-836f-aedae632ccd1.PNG)
![2](https://user-images.githubusercontent.com/54451815/106684232-d5be6a00-65a4-11eb-8db3-a5aeb711c421.PNG)
![3](https://user-images.githubusercontent.com/54451815/106684233-d6ef9700-65a4-11eb-8ceb-bae4fdb4c2b0.PNG)

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
Horse's aren't implemented yet. #116 do assure however to keep above in consideration.
