### ISSUE TITLE
[BUG]Outside the Walls inaccuracies

### ISSUE THREAD

**Issue by desu7** [AoTTG-2/AoTTG-2#532]
**Describe the bug**
The "Outside the Walls" map looks really odd, there's more hills than usual and the map geometry looks less smooth and more bumpy overall, the path texture is also incorrect, as it should be a rock texture. Even zones that are flat have small hills. This happens specially after the 4th checkpoint, and as a result of that weird geometry, the gas supplies in the 6th, 7th and 8th point are spawned below the checkpoints (you can check with specmode), but this is because the checkpoint placement in these zones is actually far below of the map's position, this also causes Titans to spawn below the map and fall to their demise. I'm unsure whether this is because the map is different but the checkpoints are in the same position as in AOTTG, or because the checkpoints were placed from scratch and those were placed wrong.

Overall, I don't know why the map looks different from AOTTG, but probably the map is divided in parts and they weren't attached properly, or the map had to be redone for some reason.

On the other hand, the checkpoints are smaller than in AOTTG (can be easily checked seeing how much space a gas supply takes in the checkpoint), but the radius where Humans and Titans can capture it is a bit bigger, so I think that maybe the size of the checkpoints weren't set properly, but their collision is the same as in AOTTG.

**To Reproduce**
1. Go to Single/Multiplayer
2. Select Outside the Walls, Capture, any difficulty.
3. Check different parts of the map, then compare them with AOTTG.

**Expected behavior**
Map should look the same as in AOTTG, or at least very similar to AOTTG, and checkpoints should have the proper size to match their collision and be settled properly so the gas supply and Titans spawn on the ground.

**Screenshots**
[Link to gallery where I show the differences of the map compared to AOTTG](https://imgur.com/a/qqQU6rm)

**Additional context**

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
This isn't classified as a bug. Outside the Walls isn't identical to its AoTTG counter part as the terrain couldn't be exported. Mapping team has already been informed of this. Will create a new issue as there isn't one yet for some reason.

**Comment by Acros5542** [comment]
For future reference, any known issues like this should also be reported to the testing team so time isn't wasted reporting things that are already known.
