### ISSUE TITLE
Revamp In-Game HUD

### ISSUE THREAD

**Issue by PoleDark** [AoTTG-2/AoTTG-2#537]
**How will this enhancement improve the game?**
A fresh look  will give the game an entirely new feel for it and truly setting it apart from the first game.

**Describe the solution you'd like**
An optimized HUD that has contains the same info as the first game, however intends to have major layout changes that will fit with the new UI designs. 

**Describe alternatives you've considered**
n/a

**Additional context** (Remove if not relevant)
The new UI can integrate the enhanced HUD notification system in #318 

**Contributor instructions** (Do not modify)
1. Determine if the enhancement is compatible with existing features
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by Lithrun** [comment]
So, in terms of UX:

- [x] HUD elements should be able to get re-positioned, re-scaled, enabled or disabled by players
- [x] TextMeshPro for any UI Text
- [x] ChatBox (Bottom right), 
- [x] Level Information (Top right)
- [x] Gamemode state (Top)
- [x] Player List (Top left). 
- [x] Leaderboard #80. This does include Level Information and the Player list
- [x] Minimap (Bottom left), 
- [x] Player state (Bottom), for humans this would be your gas, blades and skill information, for titans this would be their stamina meter.
- [x] Crosshair (Hide the double hook indicator if that keybind is disabled)
- [ ] Notifications

**Comment by gisketch** [comment]
Possible additions:

- [ ] New damage popup font and animation
- [x] Blood smear on the edges of the screen when you kill a titan (could only be activated when you get high damage)

**Comment by Acros5542** [comment]
Having a separate console for commands and the kill feed as opposed to displaying it all in the chat is something that's become popular in more recent mods such as Anarchy and would be a welcome addition to AoTTG2 in my opinion. Without it you're pretty much constantly having to toggle on and off the kill feed when you're switching from doing solo-runs to playing online, as it makes the chat pretty unusable otherwise.

**Comment by gisketch** [comment]
#318 has some cool enhancements we can add

**Comment by gisketch** [comment]
#167 will be fixed along with this issue.

"The kill feed is tied to the screen height, different resolutions can have the kill feed in the middle of their screen. It should be anchored to the top of the screen"

**Comment by nolanrdavenport** [comment]
Fixed the scaling issue with the kill feed.

**Comment by PoleDark** [comment]
Some of the HUD WIPS

![Final Design HUD Rectangular Map](https://user-images.githubusercontent.com/63149678/107373030-0b250380-6b21-11eb-8da8-60318c5b0ca8.jpg)
![Final Design HUD](https://user-images.githubusercontent.com/63149678/107373053-10824e00-6b21-11eb-9b66-3d73347f0ae6.jpg)
![Final_Design_HUD_Pop_Up_Leaderboards](https://user-images.githubusercontent.com/63149678/107373143-2728a500-6b21-11eb-94bb-3eb98ddf4766.jpg)

**Comment by nolanrdavenport** [comment]
Bugs to fix introduced by @Acros5542 

- [x] The default alignment of the HUD seems to be off depending on your resolution, mainly with the 3 items along the top.
- [x] If you have two monitors you can move HUD icons off the screen by dragging your cursor to your other monitor
- [x] The leaderboard doesn’t live update when holding tab, you have to let go of tab then press it again
- [x] You can’t spawn as a Player Titan anymore (Is this even related to this issue? Did we cause this somehow?)
- [x] If you restart the game when the UI is hidden with F1, you are stuck in spectator mode.
- [x] Flooded with null references when launching, leaving, restarting, and rejoining a game. 
- [x] #367 Occurs again on this build. 
- [x] You are still able to open the pause menu with escape while in the Change HUD menu
- [x] The killfeed no longer appears in Singleplayer
- [x] The example text in the chat when editing the HUD appears even if actual messages are already in chat.

**Comment by gisketch** [comment]
> You can’t spawn as a Player Titan anymore (Is this even related to this issue? Did we cause this somehow?)

Apparently this issue occurs on the current development branch, so we did not cause this issue.

**Comment by gisketch** [comment]
Fixed issue from #367

**Comment by gisketch** [comment]
New bugs to fix courtesy of @Acros5542 

- [x] Null references after rejoining lobbies. (due to hook indicator missing)
- [x] /clear command no longer working
- [x] Kill feed hitbox too big horizontally
- [x] Blood elements persisting across lobbies.
- [ ] Blade shimmer effect not playing when refilling
- [ ] Blade desync when canceling reload.
- [x] Lay-out to layout
- [x] Gas canister (remove green filter)

New enhancements:
- [ ] Damage combos

**Comment by gisketch** [comment]
TODO:
- [ ] InRoomChat change back to instantiation
- [ ] Scoreboard (Refactor sort button)
- [ ] Blades HUD missing references (Only update, when hits titan, or reloads) //See Blades.cs
- [x] Blood Smear null reference
- [x] Customize HUD screen button missing
- [ ] KillFeed reverse animation
