### ISSUE TITLE
Unity PlayMode & EditMode Tests Setup

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#552]
**How will this enhancement improve the game?**
Sometimes references magically disappear from a Prefab if a change occurs, without being able to see this in the version control. So, having some tests which do assure that those are present would save a lot of headaches and manual testing.

**Describe the solution you'd like**
- [ ] EditMode tests for Titan Prefab references
- [ ] Check if FluentAssertion can be used
- [x] Configure CI to support this

**Comment by play-k** [comment]
unga bunga me dont know what the fuck does this mean

**Comment by Lithrun** [comment]
> 
> 
> unga bunga me dont know what the fuck does this mean

Please don't write nonsense on issues or your permissions will get revoked.

**Comment by play-k** [comment]
ok, isnt it weird how they allow random people to write?? i thought devs or testers could write

**Comment by Lithrun** [comment]
After 5 days and 150 commits, I can confirm that this is working. Time for some cleanup and those prefab titan edit mode tests
