### ISSUE TITLE
[BUG] Hook firing sound effect still plays even with no gas

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#558]
**Describe the bug**
This is an issue that exists in AoTTG1 as well, but if you try to fire a hook with no gas, the sound effect for the hook will still play even though firing hooks is only possible with gas.

**To Reproduce**
1. Run out of gas
2. Try to fire a hook
3. Listen for the hook-firing sound effect

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by nolanrdavenport** [comment]
I addressed this issue with #547 which I merged into #205. The PR for #205 will fix the issue but it's on hold because Hero.cs is being refactored.
