### ISSUE TITLE
[PROPOSAL] is there a way for someone to play the first versions of the game?

### ISSUE THREAD

**Issue by colorblindraws** [AoTTG-2/AoTTG-2#565]
**How will this feature improve the game?**
The simplicity of the “alpha era” mechanics made for an awesome experience with a very hard game and a really enjoyable learning curve 

**Describe the solution you'd like**
I just wanted to be able to play the earlier version of the game, where the city was just grey towers and the titans were thumblike design wise

**Describe alternatives you've considered**
Maybe not the super first early ones, but definetly the ones before we got the city map and the gas system

**Contributor instructions** (Do not modify)
1. Determine if the feature is compatible with existing features and fits within the scope/design of the project
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by Alex-Mod-Bot152** [comment]
Please don't make GitHub post to ask questions. Use #questions in our Discord server
