### ISSUE TITLE
Death upon impact

### ISSUE THREAD

**Issue by KoroSensei0320** [AoTTG-2/AoTTG-2#57]
**What is the use of the feature?**
Death upon impact would help make the game more challenging and  fun (to those who wish to turn it on.) It also adds more content; if people get bored of certain modes, they can try to master this. In the future. (Over 80% of people wanted to add this feature, which likely means it would get decent use)

**Describe the solution you'd like**
If your character crashes into an object past a certain speed (should be decently fast) the character will die. Needs to be optional.

**Comment by WayneZhenLi** [comment]
So this deals directly with the state machine I'm making right now...  To do this I'd just have to add another state to the just_grounded state I have (state hero goes into if he just barely goes from flying to grounded).

**Comment by WayneZhenLi** [comment]
Oh you said any object as well.   Then I'd have to add another state branching from idle as well.

**Comment by Lithrun** [comment]
@TicExp made this feature within the Expedition Mod. You could check with him @WayneZhenLi on how he did it

**Comment by Lithrun** [comment]
Based on short investigation, issue is downgraded to Junior Developer difficulty.

Some instructions:
- [ ] When the player collides with an object, calculate the impact force, and if it's higher than "Impact Force Limit", the player will die. A detailed explanation can be found in this article: https://www.malgol.com/how-to-get-the-impact-force-of-a-collision-in-unity/
- [ ] Introduce a new property setting to GamemodeSetting class named "Impact Force". This is an integer, and when it's 0 it is disabled. Once it's higher than 0, the player death collision will be used as described from above

**Comment by Lithrun** [comment]
Additionally, please investigate and discuss if titan colliders should be exempt from the OnCollisionEnter.
