### ISSUE TITLE
Player Rebinds

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#61]
**How will this enhancement improve the game?**
Rebinds are currently managed in three different ways: default unity input, InputCode and InputCodeRC. This means that rebinding is done in three different ways. Investigate our available options, and report back to @AoTTG-2/development-team, so that we can use one system instead of three.

**Describe the solution you'd like**
One input system, on which we can extend.

- [x] Investigate Input systems that Unity offers, check the existing ones and determine which one is the best for AoTTG 2. Then report findings to @AoTTG-2/development-team and discuss.
- [x] Implementation depends on above results...
- [x] Add an option in the new solution where input can be blocked if the player is within a menu
- [x] Add an generic approach to allow players to rebind, which is very easy for developers to extend.

**Comment by BensonMachine** [comment]
@ExiMichi How is this going ? if you dont have time i can take care of this

**Comment by Lithrun** [comment]
Renamed the issue from "Player Rebinds - Technical", to "Player Rebinds" to include implementing an UI. On a technical level it all should be functional as per next commit.

**Comment by Lithrun** [comment]
- [ ] Implement FOV option
- [x] Resolve chat issue

Issue placed on hold until #166 is complete, since in order to fix the chat, the reworked chat code is required (otherwise any fix is void)
