### ISSUE TITLE
[BUG] Fix titan numbers in forest wave gamemode

### ISSUE THREAD

**Issue by FAStre** [AoTTG-2/AoTTG-2#623]
**How will this enhancement improve the game?**
The forest wave gamemode settings are different to AoTTG1, and should ideally be the same.

**Describe the solution you'd like**
- [x] Change the Titans per wave in Forest back to the correct amount (starts at 3, increases by 1 each round except for waves 5, 10, 15, and 20). If this is something controlled by the new spawn service that’s not yet been finished then it can wait (Forest already doesn’t go past wave 5 due to the lack of this new spawn service).

**Describe alternatives you've considered**
@Acros5542 can provide more feedback on the issue if needed.

**Contributor instructions** (Do not modify)
1. Determine if the enhancement is compatible with existing features
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by Acros5542** [comment]
Related to #346 as well.

**Comment by Lithrun** [comment]
Should be resolved as per #604, please check in a build once available...
