### ISSUE TITLE
[BUG] Levi's skill on horesback

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#638]
**Describe the bug**
Using Levi's skill on horseback causes him to either remain on the horse or fall off, with the attack of his special never playing. The hook that normally would spin around him during this animation still appears, yet has no impact, and Levi himself with never spin or attack. Similar effects are attainable on other characters such as when using Petra or Mikasa's special, although not as noticeable as with Levi.

**To Reproduce**
1. Go to Outside the Walls and play as Levi
2. Spawn in and mount your horse
3. Attempt to use Levi's special (if standing still you will remain mounted, if moving you may fall off)

**Expected behavior**
Levi's special typically is not usable on horseback, although if this is something intending to be changed in AoTTG2, then he should dismount the horse and play out the special normally.

**Video**
https://youtu.be/bAlSVrv2KWY

**Additional context**
Unsure if this is a bug with horses or the special abilities. If this is an issue with horses, it likely should not be resolved until the horse rework is finished.

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
Hero shouldn't be able to use special skill while on a horse. Either include for #116 or as a standalone bug issue.
