### ISSUE TITLE
[BUG] Character preference incorrectly persisted across lobbies

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#639]
**Describe the bug**
The game will attempt to retain which character you last played as when joining a new lobby, meaning if you played as Annie previously, then join a new lobby, Annie will be pre-selected as your character in the spawn menu. However, only the character is persisted correctly, and the character options such as Outfit or Loadout will default to the topmost character in the list (Levi's). If you attempt to spawn in using an Outfit or Loadout not accessible on the selected character, you will be unable to spawn.

**To Reproduce**
1. Launch and the game and go to City
2. Spawn in as Annie, then leave the lobby.
3. Join a new lobby of City, and notice Annie is selected, but her usual Outfit selections of Training Corps, Military Police, and Casual are not present, instead displaying Levi's 'Default' as her Outfit and his 'Blades' as Loadout (Annie's is normally named ODMG). Attempting to select Levi's 'AHSS' Loadout will not let you spawn.

**Expected behavior**
When previously used character is auto-selected as the default option in a new lobby, their Outfit and Loadout options should also be properly persisted and displayed.

**Video**
https://youtu.be/qXPFnug0YHw

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
There's no persistence available. @AoTTG-2/development-team either add this or reset the dropdowns when the menu is opened again as the value & display value aren't in sync.
