### ISSUE TITLE
[3D Model Request] New Supply Station model

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#64]
**Information**
Supply Stations are receiving an overhaul in AoTTG 2. Whereas in AoTTG you could only change your supplies there, within AoTTG 2 you can also change your equipment (Blades, AHSS or Thunder Spears). Additionally you can also restock your items, and change your item setup. The new Supply Station model should represent these features

**Why is this 3D Model needed?**
A new supply station model

- [x] 3D Model of the Supply Depot
- [x] Texture of the Supply Depot

**Comment by PoleDark** [comment]
![Screen Shot 2020-04-05 at 15 00 10](https://user-images.githubusercontent.com/63149678/78469441-eff4a500-7753-11ea-92a2-e73c28485c50.png)

**Comment by PoleDark** [comment]
![unknown](https://user-images.githubusercontent.com/63149678/78520715-179e4880-77fa-11ea-9fe0-99e7f60663dd.png)
texture done
