### ISSUE TITLE
[BUG] Mikasa's AHSS has no texture

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#643]
**Describe the bug**
When playing as Mikasa (or Mankasa), their AHSS has no texture.

**To Reproduce**
1. Go to any map (except for Capture game mode)
2. Select to spawn in as Mikasa with the Loadout of AHSS
3. Spawn in

**Expected behavior**
The AHSS texture should be the same across different characters.

**Screenshots**
![Screenshot (921)](https://user-images.githubusercontent.com/75679898/120454254-b8868600-c361-11eb-8dcf-650e4a88afc6.png)

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
Seems like the scriptable object for Mikasa AHSS is missing. Small one
