### ISSUE TITLE
Debug Functions

### ISSUE THREAD

**Issue by SlowDeepExhalation** [AoTTG-2/AoTTG-2#645]
**How will this feature improve the game?**
Debug functions would make it substantially easier for testers and developers to confirm the presence of bugs, as well as allowing us to study and define them much faster and more precisely.  Some bugs are extremely work intensive to examine, or almost impossible to reproduce for all but the most skilled players; isolating and fixing them would be greatly eased by simple debug tools.

**Describe the solution you'd like**
Here is a list of five debug functions that have been requested specifically to ease testing certain mechanics, arranged in order of priority:
1. **Teleport command which can be given any xyz value**  (For use in _precisely_ testing ODM mechanics, as well as maps.)
2. **Player xyz coordinates, ideally always visible onscreen** (As a supplement to teleports, and for testing maps.)
3. **Noclip; the ability to totally disable collision, allowing the player to fly through titans and walls** (For testing high speed titan bugs like 2FU.  MUST allow blade hits to still kill titans.)
4. **Titan movement and rotation disable, while still allowing titan attacks** (For testing a variety of titan mechanics, from dismemberment to their attack hitboxes.)
5. **Titan attack disable** (For testing titan gameplay and behavior without attacks complicating the tests.)
6. ~~**Toggle option to show hitboxes** (Very useful for seeing if they're moving properly, scaled weird, judging hit detection, and more.)~~ [Separate issue](https://github.com/AoTTG-2/AoTTG-2/issues/657)

Isk#2728 suggested creating a GUI menu, accessed with F7, that contains all debug options.  This would be ideal, as chat commands can be forgotten by old testers, or missed by new ones.

**Describe alternatives you've considered**
Not adding debug commands, which will slow development.  ;P

**Contributor instructions** (Do not modify)
1. Determine if the feature is compatible with existing features and fits within the scope/design of the project
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by Acros5542** [comment]
Added 6. Toggle option to show hitboxes, possibly could be higher on the list, depends on what's being tested

**Comment by Lithrun** [comment]
> 
> 
> Added 6. Toggle option to show hitboxes, possibly could be higher on the list, depends on what's being tested

@Acros5542 This needs to be a new issue, as effort for that alone is probably around 2. Please do not add additional workload to an estimated issue as otherwise 1-5 has to wait until 6 is done.

See: https://github.com/AoTTG-2/AoTTG-2/issues/657
