### ISSUE TITLE
[3D Model Request] Titan Tree

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#66]
**Information**
Develop Trees which can be used for Titan Forests in the new upcoming maps. The average tree in a titan forest was said to be 80m tall.

**Why is this 3D Model needed?**
The existing trees aren't that large, and can block titan movement. They also can use some improvements, so inspire your model from references.

**References**
https://randomc.net/image/Shingeki%20no%20Kyojin/Shingeki%20no%20Kyojin%20-%2034%20-%20Large%2007.jpg
https://attackontitan.fandom.com/wiki/Titan_Forest

**Comment by KoroSensei0320** [comment]
- mistakenly added myself as an assignee. 
ErenG will be working on this issue.
