### ISSUE TITLE
[BUG] Speedometer

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#662]
**Describe the bug**
The speedometer currently rounds up to the nearest .1 (so for example if you're going fast enough to hit 2690, the speedometer will display your speed as 2.7K). This is not the same as AoTTG, in which it floors the numbers so it won't show 2.7K until you're at least going fast enough to hit 2,700 damage.
Rounding up sounds more logical on paper, but in practice it's a little misleading because it baits you into thinking you're about to hit higher than you actually will.

**Additional context**
Hi @sxlksxskul <3

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
So use this https://docs.unity3d.com/ScriptReference/Mathf.Floor.html

**Comment by sxlksxskul** [comment]
yup just have to wait to change branches which takes a million years for me
