### ISSUE TITLE
[3D Model Request]

### ISSUE THREAD

**Issue by Dvid000** [AoTTG-2/AoTTG-2#665]
**Information**
Describe what the object should look like, and be able to do.

**Why is this 3D Model needed?**
A clear and concise description of the importance of this model.

**References**
Include images which can be used as a reference for the 3D artist.

**Comment by Lithrun** [comment]
@Dvid000 was this made by accident? As there's no description within this issue

**Comment by Prolonpo** [comment]
Also noticed this weirdness, issue closed as there is no detail present.
