### ISSUE TITLE
New Titan Models

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#67]
**Working on this task with multiple contributors is required**
_It will take a while before these new models appear in the game, since animations are also required._

**Is your feature request related to a problem? Please describe.**
Existing titans always look the same. The only thing that is changeable about them is their hair, and skin (body, hair, eyes). In the source material, every titan looks unique. Thereby, it is desired that new models for titans are created. Titan body parts can have different models, similar to how a player character works. This applies for:

- [x] Head

- [ ] Hair

- [x] Arms

- [x] Body

- [x] Legs

Each of these components can get resized as well, so keep that in mind.

**Describe the solution you'd like**
A new titan model which can have different body parts, so that every titan can feel truly unique.

- [x] Create designs of how the new titan could look like. Define a style, once we have three different drafts, we will do a community poll and choose one style.

**Comment by KoroSensei0320** [comment]
Added myself to show that someone is working on it, though I don't believe they have a GitHub.

**Comment by Alex-Mod-Bot152** [comment]
Idea by @IRI 

Reference post-https://discord.com/channels/681641241125060652/683376807101071489/792089615603073074

Some titans having visible ribs that are outside of the body

**Comment by KoroSensei0320** [comment]
Everything besides hair/hair textures is complete.
