### ISSUE TITLE
Blade,Gas hud

### ISSUE THREAD

**Issue by WizardOfXerox** [AoTTG-2/AoTTG-2#670]
**How will this feature improve the game?**
Customization of the Huds like a skin

**Describe the solution you'd like**
Like a image it can be loaded like a skin

**Describe alternatives you've considered**

**Contributor instructions** (Do not modify)
1. Determine if the feature is compatible with existing features and fits within the scope/design of the project
2. If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
3. Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
4. Once the issue matches the current milestone, follow development procedures.

**Comment by Prolonpo** [comment]
@WizardOfXerox Have you received permission from any Proposal Member for posting this idea here?

The idea is good though

**Comment by Prolonpo** [comment]
Transferred the content to #318 as this issue is fairly brief.

Issue closed for the sake of de-cluttering the GitHub issues.
