### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#691]
**How will this feature improve the game?**
Thanks to the composers, we now have a nice collection of OST & sound effects. So, now let's implement these within the game.

**Describe the solution you'd like**

- [x] crossfade between states

- [x] playlists should support adding multiple songs of the same stateType

- [x] when in a specific state, and a song ends, it should change to a random song of the same stateType

- [x] playlists should be easy to make/edit and are to be made for a specific map or specific gamemodes

**Comment by Prolonpo** [comment]
Proposal Team's feedback:
- The art team already had previously mentioned that the music should be dynamic, which the Proposal Team definitely agrees on this point
- The game should have a detection system to know when titans are nearby and when players are engaging titans (for example, flying peacefully should have a different ost playing than flying with crawlers and punks chasing the player)

- If possible, OST should be labelled with sections where the transition could be made flawlessly (beats, music becoming less intense)
- If the above is not possible, then it would be possible to implement a fade-out and fade-in for the audio when the environment or the situation changes for the player.
