### ISSUE TITLE
[3D Model Request] Supply Wagon

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#70]
**Information**
There was the idea to have an NPC roam around a map with a wagon of supplies. The NPC will stop at a specified path, deploy a flare and players can refill their supplies. After several minutes, the NPC will move again to another location. Develop a wagon model for this, which can be attached to a horse.

**References**
https://www.youtube.com/watch?v=B4dIgqY4k4o (But with supplies instead of corpses >.>)

- [x] Wagon Model

- [x] Wagon Texture

**Comment by PoleDark** [comment]
![Screen Shot 2020-04-07 at 09 20 37](https://user-images.githubusercontent.com/63149678/78634493-ac767400-78d6-11ea-8db0-3329681d1de2.png)
here is your wagon with cor- supply

**Comment by Lithrun** [comment]
Model and texture are almost ready

**Comment by roxnsteady** [comment]
This has been finished for a while. Will upload the files shortly.

**Comment by roxnsteady** [comment]
[wagonModel+Texture.zip](https://github.com/AoTTG-2/AoTTG-2/files/5580897/wagonModel%2BTexture.zip)

Credit goes to PoleDark and Tony Twohands for both the texture(s) and model. Great-o jobbu!

**Comment by Prolonpo** [comment]
Additional detail from @~L~ which is around different types of wagons: Supply, transport, and corpse wagons.

See the following for more detail: https://discord.com/channels/681641241125060652/683376807101071489/783888289958592524
