### ISSUE TITLE
[BUG]Weapon trail not disappearing 

### ISSUE THREAD

**Issue by ArmoredCat0** [AoTTG-2/AoTTG-2#725]
**Describe the bug**
If you hook a wall or gas burst when the trail is visible, it won't disappear until a normal or special attack is performed.
**NOTE: The build in which this issue/bug is present has currently not merged with any of the major alpha builds**

**To Reproduce**
1. Get on any map and hook a wall or gas burst when the trail is visible i.e hook a wall while in attack animation

**Expected behavior**
The trail should disappear after the attack animation is cancelled due to hooking an object or doing a gas burst and should not be visible 

**Screenshots**
![image](https://user-images.githubusercontent.com/89747361/138043859-20c2a0f8-3b07-4e99-88fb-e609add21df8.png)

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Mi-Sad** [comment]
interesting, might have to do with the way it exit the "attack state"

**Comment by Acros5542** [comment]
We need a build to confirm this is fixed before it can be closed.

**Comment by dark3art** [comment]
this is tested and pushed into dev so imma close it
