### ISSUE TITLE
[BUG] FPS Counter Inaccuracy

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#732]
**Describe the bug**
The FPS counter does not update update as often as it should, and the number it displays is sometimes higher or lower than what your FPS actually is. The more FPS you have, the further above or below the counter may be.

**To Reproduce**
1. Use some form of external FPS tracker and launch AoTTG2
2. Compare your actual FPS to what the FPS tracker in-game displays

**Expected behavior**
The FPS tracker should update more often (perhaps every 1-2 seconds) and should be accurate to what your actual FPS is.

**Video**
The green number at the top left is my actual FPS. The smaller green number at the bottom left is the in-game FPS tracker.
https://youtu.be/y-5mNt3FqGs

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Mi-Sad** [comment]
Yeah saw and is actually bothering me so gonna fix in a sec

**Comment by Acros5542** [comment]
Same as #725, wait till a build is made to confirm it's fixed, then the bug report can be closed.
