### ISSUE TITLE
Interrupting the reloading animation can result in an invisible blade. [BUG]

### ISSUE THREAD

**Issue by PeteAniDev** [AoTTG-2/AoTTG-2#752]
**Describe the bug**
The title described its all.

**To Reproduce**
1. Spawn as a hero.
2. Reload.
3. Hook to interrupt the reload.
4. Kill titans with the invisible blade.

**Expected behavior**
Interrupting reload animation should make the hero fail to reload and have to reload again.
The HUD should also display that you haven't reloaded yet.

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Zynku** [comment]
The way this has been fixed is that if the "reload" animation is interrupted, it will act as if it hasn't been interrupted, and give the player the new blade anyway. It doesn't force the player to retry to reload like @PeteAniDev suggested.
