### ISSUE TITLE
[BUG] crosshair adjustment

### ISSUE THREAD

**Issue by dark3art** [AoTTG-2/AoTTG-2#765]
**Describe the bug**
There's an issue with the crosshair. Left hooks land much lower than expected, whereas right hooks land much higher than expected. Which as you can imagine, makes it quite annoying to test ODMG logic. Issue did not occur before https://github.com/AoTTG-2/AoTTG-2/commit/083f550fd58b0cf09d7c253301ff472776d05f5b, and was caused somewhere during the Pull Requests

**To Reproduce**
1. Aim at something with your hooks
2. Left hook will hit below the crosshair whereas the right hook will hit above the crosshair

**Expected behavior**
It's expected that the hook will land exactly where the crosshair aimed it at

**Screenshots**

**Log file**
Include a log file

**Additional context**

**Contributor instructions** (Do not modify)
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment]
Making this highest priority currently. Let's see who can fix it the fastest

**Comment by Grizzly182** [comment]
I'll try working on it too

**Comment by Zoap** [comment]
@Grizzly182  I tested this a couple days ago, try to use the branch for issue #733 to look for the bug, it seems to be related to framerate and 733 has the framerate unlocked ingame, it seems higher framerate = better accuracy, while lower framerate = less accuracy.

**Comment by mwnDK1402** [comment]
~~We need to make a decision on whether the hooks should shoot directly forwards, or whether they should always head straight towards the raycast hit point.~~
