### ISSUE TITLE
[3D Model Request] Trainee Corps Building Assets

### ISSUE THREAD

**Issue by CoronaryLilim** [AoTTG-2/AoTTG-2#91]
**Information**
Barracks: A set of wooden buildings, maybe 2 stories tall, made for housing soldiers. Interiors are completely unnecessary.
Tower: Large tower with an area atop it covered by a roof. Assumedly for the people in charge to watch all the trainees at once, but i don't see any real use for it.
Armories: Small buildings/sheds for storing ODMG, blades, gas, and so on.
ODM Training equipment: A tripod esque thing that would hold a trainee in air as though they were using ODMG, to teach them/ensure that they have balance skills.

**Why is this 3D Model needed?**
Assets for the creation of maps. The barracks and armories could easily be reused for other maps where the trainee corps aren't relevant.

**References**
![image](https://user-images.githubusercontent.com/49127711/79691717-67c7d280-821e-11ea-807a-2ef0dc44a9a4.png)
![image](https://user-images.githubusercontent.com/49127711/79691744-7f9f5680-821e-11ea-9346-d77423388e1f.png)

**Comment by MohammedOmarPF** [comment]
Uploaded the models on discord. Sorry for the long wait.
Is there anything else missing here or should this be closed?
![image](https://user-images.githubusercontent.com/64723949/81346261-48ec8b80-90ba-11ea-8d76-6931454d3a94.png)

**Comment by MohammedAlsayedOmar** [comment]
Uploaded the models on discord. Sorry for the long wait.
Is there anything else missing here or should this be closed?

![Uploaded Image](https://user-images.githubusercontent.com/64723949/81346261-48ec8b80-90ba-11ea-8d76-6931454d3a94.png)
