### ISSUE TITLE
Implement Sound

### ISSUE THREAD

**Issue by AlexWolski** [AoTTG-2/AoTTG-2#98]
**Describe the Enhancement**
All of the sound files are currently missing from the game. This enhancement will add them back in and perhaps add new sounds or update existing ones.

**Vanilla Sound Clips**
https://drive.google.com/file/d/12yOXCFHTxAiVwP25B0MngjrV5rYIy3_7/view?usp=sharing

**Describe the solution you'd like**

- [x] Add the sound files in an organized folder with proper file names
- [x] Add references to the sound files on any prefab where they are missing

**Comment by DVyse** [comment]
missing audio:
asset/resources/fx

bite
boom1
boom1_CT_kick
boom2
boom3
boom4
shotgun
shotgun1

missing prefab:

Fx12704_f_knSWP1.ogg
Fx12725_snikt.ogg
ropes_clip_1_1.ogg
sb.ogg
02zd008.ogg

**Comment by Lithrun** [comment]
Would be nice to include this one, but low priority for Alpha Build milestone.

**Comment by Lithrun** [comment]
Titan footstep sounds are missing, yet these will be added in #199
